'use client';

import React, { useState, useEffect, useCallback, useRef } from 'react';
import {
  Tv,
  QrCode,
  Sparkles,
  Maximize2,
  Clock,
  Wifi,
  WifiOff,
  Coffee,
  CheckCircle,
  CheckCircle2,
  Play,
  Pause,
  RefreshCw,
  Heart,
  RotateCw,
  Radio,
} from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { BusinessSettingsService } from '@/lib/services/business-settings.service';
import { MemoriesArchIcon } from '@/components/brand/MemoriesLogo';
import { CoBrandingLogos } from '@/components/brand/CoBrandingLogos';
import { RealOutsourcedQr } from '@/components/ui/RealOutsourcedQr';

interface WallClientProps {
  screenId: string;
}

interface WallMemoryItem {
  id: string;
  customerName: string;
  avatarUrl?: string;
  photoUrl: string;
  caption?: string;
  visitNumber: number;
  timeFormatted: string;
  createdAt: string;
}

export function WallClient({ screenId }: WallClientProps) {
  // Check if screen is already paired
  const [isPaired, setIsPaired] = useState<boolean>(() => {
    if (typeof window === 'undefined') return true;
    return localStorage.getItem(`memories_wall_paired_${screenId}`) === 'true' || screenId === 'demo';
  });

  // Dynamic Random 6-Digit Code generated by the TV Screen
  const [screenPairingCode, setScreenPairingCode] = useState<string>(() => {
    return Math.floor(100000 + Math.random() * 900000).toString();
  });
  const [pairedSuccessMsg, setPairedSuccessMsg] = useState<string | null>(null);

  // Content & Playback State
  const [memories, setMemories] = useState<WallMemoryItem[]>([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isPlaying, setIsPlaying] = useState(true);
  const [isOnline, setIsOnline] = useState(true);
  const [lastSyncTime, setLastSyncTime] = useState<string>('الآن');
  const [isFullscreen, setIsFullscreen] = useState(false);

  const [brandName, setBrandName] = useState('Espresso Lab');
  const [brandLogoUrl, setBrandLogoUrl] = useState<string | null>(null);
  const [cafeSlug, setCafeSlug] = useState('espresso-lab');

  useEffect(() => {
    try {
      const s = BusinessSettingsService.getSettings();
      if (s?.branding?.name) setBrandName(s.branding.name);
      if (s?.branding?.logoUrl) setBrandLogoUrl(s.branding.logoUrl);
      if (s?.cafeSlug) setCafeSlug(s.cafeSlug);
    } catch {}
  }, []);

  const CACHE_KEY = `memories_wall_cache_${screenId}`;

  // 1. Offline & Heartbeat Detection
  useEffect(() => {
    const handleOnline = () => setIsOnline(true);
    const handleOffline = () => setIsOnline(false);

    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);

    // Periodic Heartbeat
    const heartbeatTimer = setInterval(async () => {
      try {
        await fetch('/api/v1/screens/heartbeat', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            screenId,
            status: 'online',
          }),
        });
      } catch {}
    }, 45000);

    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
      clearInterval(heartbeatTimer);
    };
  }, [screenId]);

  // 2. Pair Success Handler
  const handlePairedSuccess = useCallback((newSlug: string, newName: string) => {
    setBrandName(newName);
    setCafeSlug(newSlug);
    setPairedSuccessMsg(`تم بنجاح! تم اقتران هذه الشاشة مع (${newName})`);
    try {
      localStorage.setItem(`memories_wall_paired_${screenId}`, 'true');
      localStorage.setItem(`memories_wall_cafe_${screenId}`, newSlug);
    } catch {}

    setTimeout(() => {
      setIsPaired(true);
      setPairedSuccessMsg(null);
      fetchApprovedMemories();
    }, 1400);
  }, [screenId]);

  // 3. Real-Time Pairing Listener (BroadcastChannel + Storage Event)
  useEffect(() => {
    if (typeof window === 'undefined') return;

    // Save pending pairing code to localStorage so dashboard in another tab/window can see it
    try {
      localStorage.setItem('memories_active_tv_code', screenPairingCode);
      localStorage.setItem('memories_active_tv_screen', screenId);
    } catch {}

    let channel: BroadcastChannel | null = null;
    try {
      channel = new BroadcastChannel('memories_screens_channel');
      channel.onmessage = (event) => {
        const data = event.data;
        if (data?.type === 'SCREEN_PAIRED' && (data.code === screenPairingCode || data.code === 'all')) {
          handlePairedSuccess(data.cafeSlug || 'espresso-lab', data.cafeName || 'Espresso Lab');
        }
      };
    } catch {}

    const handleStorage = (e: StorageEvent) => {
      if (e.key === `memories_paired_screen_${screenPairingCode}` && e.newValue) {
        try {
          const parsed = JSON.parse(e.newValue);
          handlePairedSuccess(parsed.cafeSlug || 'espresso-lab', parsed.cafeName || 'Espresso Lab');
        } catch {}
      }
    };
    window.addEventListener('storage', handleStorage);

    return () => {
      if (channel) channel.close();
      window.removeEventListener('storage', handleStorage);
    };
  }, [screenPairingCode, screenId, handlePairedSuccess]);

  // 4. Fetch Live Approved Memories with Offline Cache Fallback
  const fetchApprovedMemories = useCallback(async () => {
    try {
      const res = await fetch('/api/v1/memories?status=approved&visibility=live_wall&limit=30');
      if (res.ok) {
        const data = await res.json();
        if (data.memories && data.memories.length > 0) {
          const mapped: WallMemoryItem[] = data.memories.map((m: any, idx: number) => ({
            id: m.id,
            customerName: m.customers?.display_name || 'عميل مميز',
            avatarUrl: m.customers?.avatar_url,
            photoUrl: m.optimized_url || m.original_url,
            caption: m.caption,
            visitNumber: m.customers?.total_visits || idx + 1,
            timeFormatted: new Date(m.created_at).toLocaleTimeString('ar-EG', {
              hour: '2-digit',
              minute: '2-digit',
            }),
            createdAt: m.created_at,
          }));

          setMemories(mapped);
          setLastSyncTime(new Date().toLocaleTimeString('ar-EG', { hour: '2-digit', minute: '2-digit' }));
          try {
            localStorage.setItem(CACHE_KEY, JSON.stringify(mapped));
          } catch {}
          return;
        }
      }
    } catch {
      console.warn('API fetch failed, falling back to local storage cache');
    }

    // Fallback to local storage
    try {
      const cached = localStorage.getItem(CACHE_KEY);
      if (cached) {
        setMemories(JSON.parse(cached));
      }
    } catch {}
  }, [CACHE_KEY]);

  useEffect(() => {
    fetchApprovedMemories();
    const pollInterval = setInterval(fetchApprovedMemories, 30000);
    return () => clearInterval(pollInterval);
  }, [fetchApprovedMemories]);

  // 5. Slideshow Transition Timer
  useEffect(() => {
    if (!isPlaying || memories.length <= 1) return;
    const timer = setInterval(() => {
      setCurrentIndex((prev) => (prev + 1) % memories.length);
    }, 8000);
    return () => clearInterval(timer);
  }, [isPlaying, memories.length]);

  // Refresh pairing code
  const handleRegenerateCode = () => {
    const newCode = Math.floor(100000 + Math.random() * 900000).toString();
    setScreenPairingCode(newCode);
    try {
      localStorage.setItem('memories_active_tv_code', newCode);
    } catch {}
  };

  // Toggle Fullscreen
  const toggleFullscreen = () => {
    if (!document.fullscreenElement) {
      document.documentElement.requestFullscreen().catch(() => {});
      setIsFullscreen(true);
    } else {
      document.exitFullscreen().catch(() => {});
      setIsFullscreen(false);
    }
  };

  const currentMemory = memories[currentIndex] || memories[0];

  // -------------------------------------------------------------
  // UNPAIRED STATE: Display 6-Digit Screen Pairing Code to Merchant
  // -------------------------------------------------------------
  if (!isPaired) {
    return (
      <div className="min-h-screen bg-stone-950 text-white flex flex-col items-center justify-between p-6 sm:p-12 select-none font-cairo relative overflow-hidden">
        {/* Subtle Ambient Glow */}
        <div className="absolute top-1/3 left-1/2 -translate-x-1/2 w-[700px] h-[500px] bg-amber-500/10 rounded-full blur-[160px] pointer-events-none" />

        {/* Top Header */}
        <div className="w-full flex items-center justify-between z-10 border-b border-stone-800/80 pb-4">
          <CoBrandingLogos
            cafeName={brandName}
            cafeLogoUrl={brandLogoUrl}
            size="md"
            theme="dark"
            showTagline={true}
          />
          <div className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-stone-900 border border-stone-800 text-xs font-mono text-amber-400">
            <Radio className="w-3.5 h-3.5 animate-pulse" />
            <span>Smart TV Receiver Ready</span>
          </div>
        </div>

        {/* Main Pairing Code Display */}
        <div className="max-w-2xl w-full p-8 sm:p-12 rounded-3xl bg-stone-900/90 border border-stone-800/90 shadow-2xl text-center space-y-6 z-10 backdrop-blur-md">
          {pairedSuccessMsg ? (
            <div className="p-6 rounded-2xl bg-emerald-950/80 border border-emerald-500/50 text-emerald-300 space-y-3 animate-in zoom-in-95 duration-300">
              <CheckCircle2 className="w-14 h-14 text-emerald-400 mx-auto animate-bounce" />
              <h3 className="text-xl font-black">{pairedSuccessMsg}</h3>
              <p className="text-xs text-emerald-400/80">جاري بدء بث الذكريات والصور المعتمدة فوراً...</p>
            </div>
          ) : (
            <>
              <div className="w-16 h-16 rounded-3xl bg-amber-500/20 text-amber-400 flex items-center justify-center mx-auto border border-amber-500/40 shadow-[0_0_30px_rgba(245,158,11,0.25)]">
                <Tv className="w-8 h-8" />
              </div>

              <div className="space-y-2">
                <h1 className="text-2xl sm:text-3xl font-black text-white tracking-tight">
                  اقتران شاشة التلفزيون الذكية (TV Wall)
                </h1>
                <p className="text-xs sm:text-sm text-stone-400 max-w-lg mx-auto leading-relaxed">
                  أدخل هذا الرقم المكون من 6 أرقام في <span className="text-amber-400 font-bold">لوحة تحكم التاجر (Merchant Dashboard)</span> لربط هذه الشاشة مع فرعك وبث لحظات الزوار فورياً:
                </p>
              </div>

              {/* Huge 6-Digit Screen Code */}
              <div className="py-2" dir="ltr">
                <div className="flex items-center justify-center gap-2.5 sm:gap-4 font-mono font-black text-3xl sm:text-6xl">
                  {screenPairingCode.split('').map((digit, idx) => (
                    <div
                      key={idx}
                      className="w-12 h-16 sm:w-20 sm:h-26 rounded-2xl bg-stone-950 border-2 border-amber-500/70 text-amber-400 flex items-center justify-center shadow-[0_0_20px_rgba(245,158,11,0.2)] hover:border-amber-400 transition"
                    >
                      {digit}
                    </div>
                  ))}
                </div>
              </div>

              {/* Simple Step-by-Step Guide */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-right pt-2">
                <div className="p-3 rounded-xl bg-stone-950/70 border border-stone-800 text-[11px] text-stone-300">
                  <span className="font-mono font-black text-amber-400 block mb-1">الخطوة 1:</span>
                  افتح لوحة تحكم التاجر على هاتفك أو جهازك.
                </div>
                <div className="p-3 rounded-xl bg-stone-950/70 border border-stone-800 text-[11px] text-stone-300">
                  <span className="font-mono font-black text-amber-400 block mb-1">الخطوة 2:</span>
                  انتقل إلى تبويب «شاشات الصالة» واضغط اقتران.
                </div>
                <div className="p-3 rounded-xl bg-stone-950/70 border border-stone-800 text-[11px] text-stone-300">
                  <span className="font-mono font-black text-amber-400 block mb-1">الخطوة 3:</span>
                  اكتب الرمز الظاهر أعلاه ({screenPairingCode}) واضغط تأكيد.
                </div>
              </div>

              {/* Listening Status & Actions */}
              <div className="flex flex-wrap items-center justify-center gap-4 pt-4 border-t border-stone-800 text-xs">
                <div className="flex items-center gap-2 text-stone-400">
                  <span className="w-2.5 h-2.5 rounded-full bg-amber-400 animate-ping" />
                  <span>بانتظار إدخال الكود من التاجر...</span>
                </div>

                <button
                  type="button"
                  onClick={handleRegenerateCode}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-stone-800 hover:bg-stone-700 text-stone-300 transition text-[11px] cursor-pointer"
                >
                  <RotateCw className="w-3.5 h-3.5" />
                  <span>توليد كود جديد</span>
                </button>

                <button
                  type="button"
                  onClick={() => setIsPaired(true)}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-amber-500/20 hover:bg-amber-500/30 text-amber-300 border border-amber-500/40 transition text-[11px] cursor-pointer font-bold"
                >
                  <span>معاينة حية فورية للشاشة ←</span>
                </button>
              </div>
            </>
          )}
        </div>

        {/* Footer */}
        <div className="text-center text-xs text-stone-500 font-mono z-10">
          Screen ID: {screenId} • Powered by memories Live Signage Engine
        </div>
      </div>
    );
  }

  // -------------------------------------------------------------
  // PAIRED STATE: Live TV Wall Broadcast Display
  // -------------------------------------------------------------
  return (
    <div className="min-h-screen bg-[#0E0C0A] text-[#FAF6EE] flex flex-col justify-between p-6 sm:p-10 select-none overflow-hidden font-cairo relative">
      {/* Background Ambient Spotlight */}
      <div className="absolute top-1/4 left-1/4 w-[600px] h-[600px] bg-amber-600/10 rounded-full blur-[140px] pointer-events-none" />

      {/* Top Header Bar: MEMORIES × BRAND Side-by-Side */}
      <header className="relative z-20 flex items-center justify-between border-b border-stone-800 pb-5">
        <CoBrandingLogos
          cafeName={brandName}
          cafeLogoUrl={brandLogoUrl}
          size="md"
          theme="dark"
          showTagline={true}
        />

        {/* Status indicators & subtle controls */}
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-stone-900 border border-stone-800 text-xs font-mono">
            {isOnline ? (
              <Wifi className="w-3.5 h-3.5 text-emerald-400" />
            ) : (
              <WifiOff className="w-3.5 h-3.5 text-amber-500" />
            )}
            <span className="text-stone-300">
              {isOnline ? 'LIVE 4K' : 'OFFLINE CACHE'}
            </span>
          </div>

          <button
            onClick={() => setIsPaired(false)}
            className="px-2.5 py-1.5 rounded-xl bg-stone-900 hover:bg-stone-800 border border-stone-800 text-stone-400 hover:text-white text-[11px] transition cursor-pointer font-mono"
            title="إعادة اقتران الشاشة"
          >
            كود الشاشة
          </button>

          <button
            onClick={toggleFullscreen}
            className="p-2.5 rounded-xl bg-stone-900 hover:bg-stone-800 border border-stone-800 text-stone-200 transition cursor-pointer"
            title="ملء الشاشة"
          >
            <Maximize2 className="w-4 h-4" />
          </button>
        </div>
      </header>

      {/* Main Community Board Stage */}
      <main className="relative z-10 flex-1 my-6 flex flex-col lg:flex-row items-center justify-center gap-8 lg:gap-14">
        {currentMemory ? (
          <>
            {/* The Photo Strip / Polaroid Frame */}
            <div className="relative group max-w-md w-full aspect-[3/4] max-h-[70vh] rounded-3xl overflow-hidden shadow-2xl border-4 border-[#2A241E] bg-[#14120F] flex items-center justify-center">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={currentMemory.photoUrl}
                alt={currentMemory.customerName}
                className="w-full h-full object-cover animate-in fade-in zoom-in-95 duration-700"
              />

              {/* Subtle Gradient & Badge */}
              <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-black/20 pointer-events-none" />

              {/* Bottom Memory Caption */}
              <div className="absolute bottom-0 inset-x-0 p-6 text-right space-y-1 z-10">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-mono text-[#D4AF37] font-bold px-2.5 py-0.5 rounded-full bg-black/50 backdrop-blur-sm border border-[#D4AF37]/30">
                    الزيارة رقم #{currentMemory.visitNumber}
                  </span>
                  <span className="text-xs font-mono text-stone-400">
                    {currentMemory.timeFormatted}
                  </span>
                </div>
                <h3 className="text-xl font-black text-white drop-shadow-md">
                  {currentMemory.customerName}
                </h3>
                {currentMemory.caption && (
                  <p className="text-sm text-stone-300 drop-shadow-sm font-medium">
                    "{currentMemory.caption}"
                  </p>
                )}
              </div>
            </div>

            {/* Side Call-to-Action & Community QR */}
            <div className="flex flex-col items-center lg:items-start text-center lg:text-right space-y-6 max-w-sm">
              <div className="space-y-2">
                <span className="px-3.5 py-1 rounded-full bg-amber-500/20 text-amber-400 font-mono text-xs font-bold border border-amber-500/30 inline-block">
                  لحظات وذكريات الصالة
                </span>
                <h2 className="text-2xl sm:text-3xl font-black text-white leading-tight">
                  شارك ذكرياتك لتظهر هنا على شاشة الكافيه
                </h2>
                <p className="text-sm text-stone-400 leading-relaxed">
                  امسح الرمز بكاميرا هاتفك، التقط صورك في استوديو الذكريات، واختم كارت ولائك للحصول على هديتك.
                </p>
              </div>

              {/* Real Scannable High-Contrast QR Code */}
              <div className="p-4 rounded-3xl bg-white shadow-2xl flex flex-col items-center gap-2 border-2 border-amber-500/50">
                <RealOutsourcedQr
                  value={`https://memories-c9w.pages.dev/c/${cafeSlug}?source=live_wall`}
                  size={144}
                  alt="Live Wall QR"
                  className="w-36 h-36 object-contain"
                />
                <span className="text-[10px] font-mono font-black text-stone-900 tracking-wider">
                  SCAN TO JOIN THE WALL
                </span>
              </div>
            </div>
          </>
        ) : (
          <div className="text-center space-y-4 max-w-md p-8 rounded-3xl bg-stone-900/60 border border-stone-800">
            <Sparkles className="w-12 h-12 text-amber-400 mx-auto animate-pulse" />
            <h3 className="text-xl font-bold text-white">بانتظار اللقطة الأولى اليوم</h3>
            <p className="text-xs text-stone-400 leading-relaxed">
              امسح الرمز عند طاولتك أو الكاونتر لتكون صورتك أول ذكرى تضيء شاشة الصالة اليوم!
            </p>
            <div className="p-3 bg-white rounded-2xl w-32 h-32 mx-auto flex items-center justify-center shadow-lg">
              <RealOutsourcedQr
                value={`https://memories-c9w.pages.dev/c/${cafeSlug}?source=live_wall`}
                size={112}
                alt="Live Wall QR"
              />
            </div>
          </div>
        )}
      </main>

      {/* Bottom Footer Ticker */}
      <footer className="relative z-20 flex items-center justify-between border-t border-stone-800/80 pt-4 text-xs text-stone-400 font-mono">
        <div className="flex items-center gap-2">
          <Clock className="w-3.5 h-3.5 text-stone-500" />
          <span>آخر تحديث: {lastSyncTime}</span>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={() => setIsPlaying(!isPlaying)}
            className="flex items-center gap-1.5 px-3 py-1 rounded-full bg-stone-900 hover:bg-stone-800 border border-stone-800 text-stone-300 transition text-[11px] cursor-pointer"
          >
            {isPlaying ? <Pause className="w-3 h-3" /> : <Play className="w-3 h-3" />}
            <span>{isPlaying ? 'إيقاف مؤقت' : 'تشغيل'}</span>
          </button>

          <span className="hidden sm:inline">
            memories Digital Signage • {cafeSlug}
          </span>
        </div>
      </footer>
    </div>
  );
}
