'use client';

import React, { useState, useEffect, useCallback, useRef } from 'react';
import {
  Tv,
  QrCode,
  Sparkles,
  Maximize2,
  Clock,
  Wifi,
  WifiOff,
  Coffee,
  CheckCircle,
  CheckCircle2,
  Play,
  Pause,
  RefreshCw,
  Heart,
  RotateCw,
  Radio,
  ArrowRight,
} from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { BusinessSettingsService } from '@/lib/services/business-settings.service';
import { MemoriesArchIcon } from '@/components/brand/MemoriesLogo';
import { CoBrandingLogos } from '@/components/brand/CoBrandingLogos';
import { RealOutsourcedQr } from '@/components/ui/RealOutsourcedQr';

interface WallClientProps {
  screenId: string;
}

interface WallMemoryItem {
  id: string;
  customerName: string;
  avatarUrl?: string;
  photoUrl: string;
  caption?: string;
  visitNumber: number;
  timeFormatted: string;
  createdAt: string;
}

const DEFAULT_FEATURED_MEMORIES: WallMemoryItem[] = [
  {
    id: 'wall-mem-1',
    customerName: 'سارة عبد الله',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    caption: 'أحلى جلسة وقهوة فلات وايت مع سارة ☕✨',
    visitNumber: 4,
    timeFormatted: 'منذ ١٠ دقائق',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wall-mem-2',
    customerName: 'فيصل وبدر',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&auto=format&fit=crop&q=80',
    caption: 'احتفال بانتهاء المشروع في مقهانا المفضل!',
    visitNumber: 7,
    timeFormatted: 'منذ ٢٥ دقيقة',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wall-mem-3',
    customerName: 'نورة المنصور',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80',
    caption: 'الكورتادو رايق جداً كالعادة 🤍',
    visitNumber: 3,
    timeFormatted: 'منذ ٤٥ دقيقة',
    createdAt: new Date().toISOString(),
  },
];

export function WallClient({ screenId }: WallClientProps) {
  // Check if screen is already paired - screen-1 defaults to true for live presentation
  const [isPaired, setIsPaired] = useState<boolean>(() => {
    if (typeof window === 'undefined') return true;
    const stored = localStorage.getItem(`memories_wall_paired_${screenId}`);
    if (stored !== null) return stored === 'true';
    return screenId === 'screen-1' || screenId === 'screen-101';
  });

  // Dynamic Random 6-Digit Code generated by the TV Screen
  const [screenPairingCode, setScreenPairingCode] = useState<string>(() => {
    return Math.floor(100000 + Math.random() * 900000).toString();
  });
  const [pairedSuccessMsg, setPairedSuccessMsg] = useState<string | null>(null);

  // Content & Playback State - initialized with curated specialty memories
  const [memories, setMemories] = useState<WallMemoryItem[]>(DEFAULT_FEATURED_MEMORIES);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isPlaying, setIsPlaying] = useState(true);
  const [isOnline, setIsOnline] = useState(true);
  const [lastSyncTime, setLastSyncTime] = useState<string>('الآن');
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [isBlackout, setIsBlackout] = useState(false);
  const [slideIntervalMs, setSlideIntervalMs] = useState(8000);
  const [newMemoryToast, setNewMemoryToast] = useState<string | null>(null);

  const [brandName, setBrandName] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('memories_active_merchant_name') || 'Espresso Lab';
    }
    return 'Espresso Lab';
  });
  const [brandLogoUrl, setBrandLogoUrl] = useState<string | null>(null);
  const [cafeSlug, setCafeSlug] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('memories_active_merchant_slug') || 'espresso-lab';
    }
    return 'espresso-lab';
  });

  useEffect(() => {
    try {
      const s = BusinessSettingsService.getSettings(cafeSlug);
      if (s?.branding?.name) setBrandName(s.branding.name);
      if (s?.branding?.logoUrl) setBrandLogoUrl(s.branding.logoUrl);
      if (s?.cafeSlug) setCafeSlug(s.cafeSlug);
    } catch {}
  }, [cafeSlug]);

  const CACHE_KEY = `memories_wall_cache_${screenId}`;

  // 1. Offline & Heartbeat Detection
  useEffect(() => {
    const handleOnline = () => setIsOnline(true);
    const handleOffline = () => setIsOnline(false);

    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);

    const heartbeatTimer = setInterval(async () => {
      try {
        await fetch('/api/v1/screens/heartbeat', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            screenId,
            status: 'online',
          }),
        });
      } catch {}
    }, 45000);

    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
      clearInterval(heartbeatTimer);
    };
  }, [screenId]);

  // 2. Pair Success Handler
  const handlePairedSuccess = useCallback((newSlug: string, newName: string) => {
    setBrandName(newName);
    setCafeSlug(newSlug);
    setPairedSuccessMsg(`تم بنجاح! تم اقتران هذه الشاشة مع (${newName})`);
    try {
      localStorage.setItem(`memories_wall_paired_${screenId}`, 'true');
      localStorage.setItem(`memories_wall_cafe_${screenId}`, newSlug);
    } catch {}

    setTimeout(() => {
      setIsPaired(true);
      setPairedSuccessMsg(null);
      fetchApprovedMemories();
    }, 1200);
  }, [screenId]);

  // 3. Fetch Live Approved Memories with Offline Cache Fallback
  const fetchApprovedMemories = useCallback(async () => {
    try {
      const res = await fetch('/api/v1/memories?status=approved&visibility=live_wall&limit=30');
      if (res.ok) {
        const data = await res.json();
        if (data.memories && data.memories.length > 0) {
          const mapped: WallMemoryItem[] = data.memories.map((m: any, idx: number) => ({
            id: m.id,
            customerName: m.customers?.display_name || 'عميل مميز',
            avatarUrl: m.customers?.avatar_url,
            photoUrl: m.optimized_url || m.original_url,
            caption: m.caption,
            visitNumber: m.customers?.total_visits || idx + 1,
            timeFormatted: new Date(m.created_at).toLocaleTimeString('ar-SA', {
              hour: '2-digit',
              minute: '2-digit',
            }),
            createdAt: m.created_at,
          }));

          setMemories(mapped);
          setLastSyncTime(new Date().toLocaleTimeString('ar-SA', { hour: '2-digit', minute: '2-digit' }));
          try {
            localStorage.setItem(CACHE_KEY, JSON.stringify(mapped));
          } catch {}
          return;
        }
      }
    } catch {
      console.warn('API fetch failed, falling back to local storage cache');
    }

    try {
      const cached = localStorage.getItem(CACHE_KEY);
      if (cached) {
        const parsed = JSON.parse(cached);
        if (Array.isArray(parsed) && parsed.length > 0) {
          setMemories(parsed);
          return;
        }
      }
    } catch {}
    setMemories(DEFAULT_FEATURED_MEMORIES);
  }, [CACHE_KEY]);

  // 4. Real-Time Pairing & Remote TV Commands Listener (BroadcastChannel + Storage Event)
  useEffect(() => {
    if (typeof window === 'undefined') return;

    try {
      localStorage.setItem('memories_active_tv_code', screenPairingCode);
      localStorage.setItem('memories_active_tv_screen', screenId);
    } catch {}

    let channel: BroadcastChannel | null = null;
    try {
      channel = new BroadcastChannel('memories_screens_channel');
      channel.onmessage = (event) => {
        const data = event.data;
        if (data?.type === 'SCREEN_PAIRED' && (data.code === screenPairingCode || data.code === 'all')) {
          handlePairedSuccess(data.cafeSlug || 'espresso-lab', data.cafeName || 'Espresso Lab');
        }
        if (data?.type === 'WALL_NEW_PHOTO' && data.item) {
          setMemories((prev) => [data.item, ...prev.filter((m) => m.id !== data.item.id)]);
          setCurrentIndex(0);
          setNewMemoryToast(`وصلت ذكرى جديدة للتو من ${data.item.customerName || 'أحد ضيوف الكافيه'}! ✨`);
          setTimeout(() => setNewMemoryToast(null), 6000);
        }
        if (data?.type === 'WALL_COMMAND') {
          if (data.command === 'BLACKOUT') {
            setIsBlackout(Boolean(data.blackout));
          } else if (data.command === 'SET_SPEED' && data.durationMs) {
            setSlideIntervalMs(data.durationMs);
          } else if (data.command === 'FORCE_REFRESH') {
            fetchApprovedMemories();
          } else if (data.command === 'UNPAIR') {
            try {
              localStorage.removeItem(`memories_wall_paired_${screenId}`);
              localStorage.removeItem(`memories_wall_cafe_${screenId}`);
            } catch {}
            setIsPaired(false);
          }
        }
      };
    } catch {}

    const handleCustomWallUpdate = (e: Event) => {
      const customEvent = e as CustomEvent;
      if (customEvent.detail && Array.isArray(customEvent.detail) && customEvent.detail.length > 0) {
        setMemories(customEvent.detail);
        setCurrentIndex(0);
        const newest = customEvent.detail[0];
        setNewMemoryToast(`وصلت ذكرى جديدة للتو من ${newest.customerName || 'أحد ضيوف الكافيه'}! ✨`);
        setTimeout(() => setNewMemoryToast(null), 6000);
      }
    };
    window.addEventListener('memories-wall-updated', handleCustomWallUpdate);

    const handleStorage = (e: StorageEvent) => {
      if (e.key === `memories_paired_screen_${screenPairingCode}` && e.newValue) {
        try {
          const parsed = JSON.parse(e.newValue);
          handlePairedSuccess(parsed.cafeSlug || 'espresso-lab', parsed.cafeName || 'Espresso Lab');
        } catch {}
      }
      if (e.key === `memories_wall_feed_${cafeSlug}` && e.newValue) {
        try {
          const parsed = JSON.parse(e.newValue);
          if (Array.isArray(parsed) && parsed.length > 0) {
            setMemories(parsed);
            setCurrentIndex(0);
            const newest = parsed[0];
            setNewMemoryToast(`وصلت ذكرى جديدة للتو من ${newest.customerName || 'أحد ضيوف الكافيه'}! ✨`);
            setTimeout(() => setNewMemoryToast(null), 6000);
          }
        } catch {}
      }
      if (e.key === 'memories_wall_command' && e.newValue) {
        try {
          const cmd = JSON.parse(e.newValue);
          if (cmd.command === 'BLACKOUT') setIsBlackout(Boolean(cmd.blackout));
          if (cmd.command === 'SET_SPEED' && cmd.durationMs) setSlideIntervalMs(cmd.durationMs);
          if (cmd.command === 'FORCE_REFRESH') fetchApprovedMemories();
          if (cmd.command === 'UNPAIR') {
            try {
              localStorage.removeItem(`memories_wall_paired_${screenId}`);
              localStorage.removeItem(`memories_wall_cafe_${screenId}`);
            } catch {}
            setIsPaired(false);
          }
        } catch {}
      }
    };
    window.addEventListener('storage', handleStorage);

    return () => {
      if (channel) channel.close();
      window.removeEventListener('storage', handleStorage);
      window.removeEventListener('memories-wall-updated', handleCustomWallUpdate);
    };
  }, [screenPairingCode, screenId, cafeSlug, handlePairedSuccess, fetchApprovedMemories]);

  useEffect(() => {
    fetchApprovedMemories();
    const pollInterval = setInterval(fetchApprovedMemories, 30000);
    return () => clearInterval(pollInterval);
  }, [fetchApprovedMemories]);

  // 5. Slideshow Transition Timer (Remotely Adjustable Speed)
  useEffect(() => {
    if (!isPlaying || memories.length <= 1) return;
    const timer = setInterval(() => {
      setCurrentIndex((prev) => (prev + 1) % memories.length);
    }, slideIntervalMs);
    return () => clearInterval(timer);
  }, [isPlaying, memories.length, slideIntervalMs]);

  // 6. Smart TV Remote Control & Keyboard Navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (document.activeElement?.tagName === 'INPUT' || document.activeElement?.tagName === 'TEXTAREA') {
        return;
      }

      if (e.code === 'Space') {
        e.preventDefault();
        setIsPlaying((prev) => !prev);
      } else if (e.key === 'f' || e.key === 'F') {
        e.preventDefault();
        toggleFullscreen();
      } else if (e.key === 'b' || e.key === 'B') {
        e.preventDefault();
        setIsBlackout((prev) => !prev);
      } else if (e.key === 'r' || e.key === 'R') {
        e.preventDefault();
        fetchApprovedMemories();
      } else if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
        e.preventDefault();
        setCurrentIndex((prev) => (prev + 1) % (memories.length || 1));
      } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
        e.preventDefault();
        setCurrentIndex((prev) => (prev - 1 + (memories.length || 1)) % (memories.length || 1));
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [memories.length, fetchApprovedMemories]);

  // Refresh pairing code
  const handleRegenerateCode = () => {
    const newCode = Math.floor(100000 + Math.random() * 900000).toString();
    setScreenPairingCode(newCode);
    try {
      localStorage.setItem('memories_active_tv_code', newCode);
    } catch {}
  };

  // Toggle Fullscreen
  const toggleFullscreen = () => {
    if (!document.fullscreenElement) {
      document.documentElement.requestFullscreen().catch(() => {});
      setIsFullscreen(true);
    } else {
      document.exitFullscreen().catch(() => {});
      setIsFullscreen(false);
    }
  };

  const currentMemory = memories[currentIndex] || memories[0];

  // -------------------------------------------------------------
  // 1. UNPAIRED STATE: Warm Ivory High-Contrast TV Screen Display
  // -------------------------------------------------------------
  if (!isPaired) {
    return (
      <div className="min-h-screen bg-[#FAF8F5] text-stone-900 flex flex-col items-center justify-between p-6 sm:p-12 select-none font-cairo relative overflow-hidden">
        {/* Subtle Warm Spotlight */}
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[700px] h-[500px] bg-amber-500/10 rounded-full blur-[140px] pointer-events-none" />

        {/* Top Header Bar */}
        <div className="w-full max-w-5xl flex items-center justify-between z-10 border-b border-stone-200/90 pb-5">
          <CoBrandingLogos
            cafeName={brandName}
            cafeLogoUrl={brandLogoUrl}
            size="lg"
            theme="light"
            showTagline={true}
          />
          <div className="flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-white border border-stone-300 text-xs font-mono font-bold text-amber-700 shadow-2xs">
            <Radio className="w-3.5 h-3.5 text-amber-600 animate-pulse" />
            <span>بث الشاشة الذكية جاهز للإقران</span>
          </div>
        </div>

        {/* Main Pairing Card */}
        <div className="max-w-2xl w-full p-8 sm:p-12 rounded-3xl bg-white border border-stone-200 shadow-xl text-center space-y-6 z-10">
          {pairedSuccessMsg ? (
            <div className="p-8 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-900 space-y-3 animate-in zoom-in-95 duration-300">
              <CheckCircle2 className="w-16 h-16 text-emerald-600 mx-auto animate-bounce" />
              <h3 className="text-2xl font-black">{pairedSuccessMsg}</h3>
              <p className="text-xs text-emerald-700 font-bold">جاري فتح شاشة العرض الحية وبث الذكريات فوراً...</p>
            </div>
          ) : (
            <>
              <div className="w-16 h-16 rounded-3xl bg-amber-50 text-amber-700 flex items-center justify-center mx-auto border border-amber-200 shadow-sm">
                <Tv className="w-8 h-8" />
              </div>

              <div className="space-y-2">
                <h1 className="text-2xl sm:text-3xl font-black text-stone-950 tracking-tight">
                  اقتران شاشة التلفزيون الذكية (Smart TV Wall)
                </h1>
                <p className="text-xs sm:text-sm text-stone-600 max-w-lg mx-auto leading-relaxed">
                  أدخل هذا الرقم المكون من 6 أرقام في <strong className="text-amber-800">لوحة تحكم التاجر</strong> لربط هذه الشاشة مع كافيهك وبث ذكريات الصالة فوراً:
                </p>
              </div>

              {/* Huge 6-Digit Screen Code */}
              <div className="py-2" dir="ltr">
                <div className="flex items-center justify-center gap-2.5 sm:gap-4 font-mono font-black text-4xl sm:text-7xl">
                  {screenPairingCode.split('').map((digit, idx) => (
                    <div
                      key={idx}
                      className="w-12 h-16 sm:w-20 sm:h-26 rounded-2xl bg-amber-50 border-2 border-amber-400 text-amber-900 flex items-center justify-center shadow-md font-mono"
                    >
                      {digit}
                    </div>
                  ))}
                </div>
              </div>

              {/* Simple Step-by-Step Guide */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-right pt-2">
                <div className="p-3.5 rounded-2xl bg-stone-50 border border-stone-200 text-xs text-stone-700">
                  <span className="font-mono font-black text-amber-700 block mb-1">الخطوة 1:</span>
                  افتح لوحة تحكم التاجر على هاتفك أو حاسوبك.
                </div>
                <div className="p-3.5 rounded-2xl bg-stone-50 border border-stone-200 text-xs text-stone-700">
                  <span className="font-mono font-black text-amber-700 block mb-1">الخطوة 2:</span>
                  انتقل إلى تبويب «شاشات الصالة».
                </div>
                <div className="p-3.5 rounded-2xl bg-stone-50 border border-stone-200 text-xs text-stone-700">
                  <span className="font-mono font-black text-amber-700 block mb-1">الخطوة 3:</span>
                  اكتب الرمز ({screenPairingCode}) واضغط «تأكيد وربط الشاشة».
                </div>
              </div>

              {/* Listening Status & Actions */}
              <div className="flex flex-wrap items-center justify-center gap-4 pt-4 border-t border-stone-100 text-xs">
                <div className="flex items-center gap-2 text-stone-500 font-bold">
                  <span className="w-2.5 h-2.5 rounded-full bg-amber-500 animate-ping" />
                  <span>بانتظار إدخال الكود من التاجر...</span>
                </div>

                <button
                  type="button"
                  onClick={handleRegenerateCode}
                  className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-stone-100 hover:bg-stone-200 text-stone-700 transition font-bold text-xs cursor-pointer"
                >
                  <RotateCw className="w-3.5 h-3.5" />
                  <span>توليد كود جديد</span>
                </button>

                <button
                  type="button"
                  onClick={() => setIsPaired(true)}
                  className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-amber-600 hover:bg-amber-700 text-white font-bold transition text-xs shadow-sm cursor-pointer"
                >
                  <span>معاينة الشاشة مباشرة ←</span>
                </button>
              </div>
            </>
          )}
        </div>

        {/* Footer */}
        <div className="text-center text-xs text-stone-400 font-mono z-10">
          Screen ID: {screenId} • Memories Smart TV Live Signage
        </div>
      </div>
    );
  }

  // -------------------------------------------------------------
  // 1.5. BLACKOUT / STANDBY STATE (Merchant Emergency or Pause)
  // -------------------------------------------------------------
  if (isPaired && isBlackout) {
    return (
      <div className="min-h-screen bg-[#FAF8F5] text-stone-900 flex flex-col items-center justify-between p-8 select-none font-cairo relative overflow-hidden">
        {/* Subtle Ambient Spotlight */}
        <div className="absolute top-1/3 left-1/2 -translate-x-1/2 w-[600px] h-[600px] bg-amber-500/10 rounded-full blur-[140px] pointer-events-none" />

        <div className="w-full max-w-5xl flex items-center justify-between z-10 border-b border-stone-200/90 pb-5">
          <CoBrandingLogos
            cafeName={brandName}
            cafeLogoUrl={brandLogoUrl}
            size="lg"
            theme="light"
            showTagline={true}
          />
          <div className="flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-amber-100/70 border border-amber-300 text-amber-900 text-xs font-bold font-mono">
            <span className="w-2 h-2 rounded-full bg-amber-500 animate-ping" />
            <span>شاشة الصالة في استراحة مؤقتة</span>
          </div>
        </div>

        <div className="text-center space-y-5 max-w-md z-10">
          <div className="w-24 h-24 rounded-3xl bg-amber-50 border-2 border-amber-200 text-amber-700 flex items-center justify-center mx-auto shadow-md animate-pulse">
            <Coffee className="w-12 h-12" />
          </div>
          <div className="space-y-2">
            <h2 className="text-3xl font-black text-stone-950 tracking-tight">{brandName}</h2>
            <p className="text-sm text-stone-600 font-bold leading-relaxed">
              شاشة العرض في وضع الاستراحة المؤقتة.
              <br />
              التقط لقطتك اليوم واطبع شريط ذكرياتك عبر مسح كود الطاولة بالهاتف!
            </p>
          </div>
        </div>

        <div className="text-center text-xs text-stone-400 font-mono z-10">
          Screen ID: {screenId} • Standby Mode
        </div>
      </div>
    );
  }

  // -------------------------------------------------------------
  // 2. PAIRED STATE: Warm Luxury Live Wall Broadcast Display
  // -------------------------------------------------------------
  return (
    <div className="min-h-screen bg-[#FAF8F5] text-stone-900 flex flex-col justify-between p-6 sm:p-10 select-none overflow-hidden font-cairo relative">
      {/* Real-time Celebration Toast Banner */}
      {newMemoryToast && (
        <div className="fixed top-8 left-1/2 -translate-x-1/2 z-50 animate-in fade-in slide-in-from-top-4 duration-500">
          <div className="flex items-center gap-3 px-6 py-3.5 rounded-2xl bg-gradient-to-r from-amber-600 to-amber-700 text-white font-bold shadow-2xl border-2 border-amber-300/40 backdrop-blur-md">
            <Sparkles className="w-5 h-5 text-amber-200 animate-spin" />
            <span className="text-sm sm:text-base tracking-wide drop-shadow-sm">{newMemoryToast}</span>
          </div>
        </div>
      )}

      {/* Background Ambient Warm Spotlight */}
      <div className="absolute top-1/4 left-1/4 w-[600px] h-[600px] bg-amber-500/10 rounded-full blur-[140px] pointer-events-none" />

      {/* Top Header Bar: MEMORIES × BRAND Side-by-Side */}
      <header className="relative z-20 flex items-center justify-between border-b border-stone-200/90 pb-5 max-w-6xl mx-auto w-full">
        <CoBrandingLogos
          cafeName={brandName}
          cafeLogoUrl={brandLogoUrl}
          size="lg"
          theme="light"
          showTagline={true}
        />

        {/* Status indicators & subtle controls */}
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-white border border-stone-200 text-xs font-mono shadow-2xs">
            {isOnline ? (
              <Wifi className="w-3.5 h-3.5 text-emerald-600" />
            ) : (
              <WifiOff className="w-3.5 h-3.5 text-amber-600" />
            )}
            <span className="text-stone-700 font-bold">
              {isOnline ? 'LIVE 4K' : 'OFFLINE CACHE'}
            </span>
          </div>

          <button
            onClick={() => setIsPaired(false)}
            className="px-3 py-1.5 rounded-xl bg-white hover:bg-stone-50 border border-stone-200 text-stone-700 text-xs transition cursor-pointer font-bold shadow-2xs"
            title="إعادة اقتران الشاشة"
          >
            كود الشاشة
          </button>

          <button
            onClick={toggleFullscreen}
            className="p-2 rounded-xl bg-white hover:bg-stone-50 border border-stone-200 text-stone-700 transition cursor-pointer shadow-2xs"
            title="ملء الشاشة"
          >
            <Maximize2 className="w-4 h-4" />
          </button>
        </div>
      </header>

      {/* Main Community Board Stage */}
      <main className="relative z-10 flex-1 my-6 flex flex-col lg:flex-row items-center justify-center gap-8 lg:gap-14 max-w-6xl mx-auto w-full">
        {currentMemory ? (
          <>
            {/* The Photo Strip / Polaroid Frame */}
            <div className="relative group max-w-md w-full aspect-[3/4] max-h-[70vh] rounded-3xl overflow-hidden shadow-2xl border-4 border-white bg-white flex items-center justify-center ring-1 ring-stone-200">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={currentMemory.photoUrl}
                alt={currentMemory.customerName}
                className="w-full h-full object-cover animate-in fade-in zoom-in-95 duration-700"
              />

              {/* Bottom Memory Caption Overlay */}
              <div className="absolute bottom-0 inset-x-0 p-6 text-right space-y-1 z-10 bg-gradient-to-t from-stone-950/80 via-stone-950/40 to-transparent text-white">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-mono text-amber-300 font-bold px-2.5 py-0.5 rounded-full bg-stone-900/60 backdrop-blur-sm border border-amber-300/30">
                    الزيارة رقم #{currentMemory.visitNumber}
                  </span>
                  <span className="text-xs font-mono text-stone-300">
                    {currentMemory.timeFormatted}
                  </span>
                </div>
                <h3 className="text-xl font-black text-white drop-shadow-md">
                  {currentMemory.customerName}
                </h3>
                {currentMemory.caption && (
                  <p className="text-sm text-stone-200 drop-shadow-sm font-medium">
                    "{currentMemory.caption}"
                  </p>
                )}
              </div>
            </div>

            {/* Side Call-to-Action & Community QR */}
            <div className="flex flex-col items-center lg:items-start text-center lg:text-right space-y-6 max-w-sm">
              <div className="space-y-2">
                <span className="px-3.5 py-1 rounded-full bg-amber-50 text-amber-800 font-mono text-xs font-bold border border-amber-200 inline-block">
                  لحظات وذكريات الصالة
                </span>
                <h2 className="text-2xl sm:text-3xl font-black text-stone-950 leading-tight">
                  شارك ذكرياتك لتظهر هنا على شاشة الكافيه
                </h2>
                <p className="text-sm text-stone-600 leading-relaxed font-medium">
                  امسح الرمز بكاميرا هاتفك، التقط صورك في استوديو الذكريات، واختم كارت ولائك للحصول على هديتك.
                </p>
              </div>

              {/* Real Scannable High-Contrast QR Code */}
              <div className="p-5 rounded-3xl bg-white shadow-xl flex flex-col items-center gap-2 border border-stone-200">
                <RealOutsourcedQr
                  value={`https://memories-c9w.pages.dev/c/${cafeSlug}?source=live_wall`}
                  size={144}
                  alt="Live Wall QR"
                  className="w-36 h-36 object-contain"
                />
                <span className="text-[10px] font-mono font-black text-stone-900 tracking-wider">
                  SCAN TO JOIN THE WALL
                </span>
              </div>
            </div>
          </>
        ) : (
          <div className="text-center space-y-4 max-w-md p-8 rounded-3xl bg-white border border-stone-200 shadow-lg">
            <Sparkles className="w-12 h-12 text-amber-600 mx-auto animate-pulse" />
            <h3 className="text-xl font-bold text-stone-950">بانتظار اللقطة الأولى اليوم</h3>
            <p className="text-xs text-stone-500 leading-relaxed">
              امسح الرمز عند طاولتك أو الكاونتر لتكون صورتك أول ذكرى تضيء شاشة الصالة اليوم!
            </p>
            <div className="p-3 bg-stone-50 rounded-2xl w-32 h-32 mx-auto flex items-center justify-center border border-stone-200">
              <RealOutsourcedQr
                value={`https://memories-c9w.pages.dev/c/${cafeSlug}?source=live_wall`}
                size={112}
                alt="Live Wall QR"
              />
            </div>
          </div>
        )}
      </main>

      {/* Bottom Footer Ticker */}
      <footer className="relative z-20 flex items-center justify-between border-t border-stone-200/90 pt-4 text-xs text-stone-500 font-mono max-w-6xl mx-auto w-full">
        <div className="flex items-center gap-2">
          <Clock className="w-3.5 h-3.5 text-stone-400" />
          <span>آخر تحديث: {lastSyncTime}</span>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={() => setIsPlaying(!isPlaying)}
            className="flex items-center gap-1.5 px-3 py-1 rounded-full bg-white hover:bg-stone-50 border border-stone-200 text-stone-700 transition text-[11px] cursor-pointer font-bold shadow-2xs"
          >
            {isPlaying ? <Pause className="w-3 h-3" /> : <Play className="w-3 h-3" />}
            <span>{isPlaying ? 'إيقاف مؤقت' : 'تشغيل'}</span>
          </button>

          <span className="hidden sm:inline">
            Memories Digital Signage • {cafeSlug}
          </span>
        </div>
      </footer>
    </div>
  );
}
