/**
 * Presets & Dimension Standards for Digital Loyalty Card Templates
 * Cafe Memories Platform
 */

import {
  LoyaltyCardDimensions,
  LoyaltyCardDimensionType,
  LoyaltyCardTemplate,
  LoyaltySlotCount,
} from '@/types/loyalty-card';

export const LOYALTY_DIMENSIONS: Record<LoyaltyCardDimensionType, LoyaltyCardDimensions> = {
  wallet: {
    type: 'wallet',
    nameEn: 'Apple Wallet Standard (ISO/IEC 7810 ID-1)',
    nameAr: 'بطاقة المحفظة القياسية (ISO 7810)',
    widthMm: 85.6,
    heightMm: 53.98,
    aspectRatio: '85.6 / 53.98',
    cssAspectRatio: '85.6 / 53.98',
    descriptionEn: 'Standard credit/loyalty card size matching Apple Wallet & Google Wallet perfectly.',
    descriptionAr: 'المقاس العالمي لبطاقات الائتمان ومحفظة آبل وجوجل، مثالي للهواتف والجيوب.',
  },
  square: {
    type: 'square',
    nameEn: 'Square Punch Card (70x70mm)',
    nameAr: 'كارت مربع كلاسيكي (70×70 مم)',
    widthMm: 70,
    heightMm: 70,
    aspectRatio: '1 / 1',
    cssAspectRatio: '1 / 1',
    descriptionEn: 'Trendy square cafe punch card, aesthetic for Instagram and table stands.',
    descriptionAr: 'تصميم مربع عصري ومميز لمقاهي الجيل الثالث وعشاق الإنستغرام.',
  },
  strip: {
    type: 'strip',
    nameEn: 'Photobooth Strip Ticket (50x140mm)',
    nameAr: 'شريط تذكرة كشك التصوير (50×140 مم)',
    widthMm: 50,
    heightMm: 140,
    aspectRatio: '50 / 140',
    cssAspectRatio: '50 / 140',
    descriptionEn: 'Vertical photobooth bookmark strip, stacking visits like memory frames.',
    descriptionAr: 'شريط تذكاري طولي يطابق شرائط كبائن التصوير الكورية، يدمج صور الزيارات رأسياً.',
  },
};

export const LOYALTY_SLOT_OPTIONS: LoyaltySlotCount[] = [4, 6, 8, 10, 12];

/**
 * 4+ Distinctive Authentic Templates for Specialty Cafes & Boutiques
 */
export const LOYALTY_CARD_PRESETS: Record<string, LoyaltyCardTemplate> = {
  espresso_pass: {
    id: 'espresso_pass',
    nameEn: 'Espresso Pass',
    nameAr: 'جواز الإسبريسو الفاخر',
    description: 'Dark matte Italian leather texture with warm bronze metallic foil stamps and stitched border.',
    descriptionAr: 'جلد إيطالي داكن مع أختام رقائق البرونز المعدنية وغرز مطرزة فاخرة لعشاق القهوة المختصة.',
    dimensionType: 'wallet',
    dimensions: LOYALTY_DIMENSIONS.wallet,
    slotCount: 10,
    badgeText: 'MEMORIES BLACK VIP',
    badgeTextAr: 'عضوية ذكريات VIP',
    tagline: 'Specialty Coffee Loyalty',
    taglineAr: 'برنامج ولاء القهوة المختصة',
    termsAndConditions: [
      'Present this digital card to the barista at each order.',
      'Milestones are automatically redeemed upon unlocking.',
      'Valid at all Memories partner branches.',
    ],
    termsAndConditionsAr: [
      'أبرز رمز الـ QR للباريستا عند كل طلب لاحتساب الختم.',
      'تُصرف المكافآت المرحلية فور اكتمال عدد الأختام المطلوب.',
      'سارية في جميع فروع ومقاهي شبكة ذكريات.',
    ],
    milestones: [
      {
        slot: 5,
        rewardTitle: 'قهوة اليوم مجانية',
        rewardTitleEn: 'Free Filter / Drip Coffee',
        rewardDescription: 'استمتع بكوب قهوة مجاني بعد 5 زيارات',
        icon: 'coffee',
        discountPercent: 100,
        codePrefix: 'ESP-DRIP',
        isGrandPrize: false,
      },
      {
        slot: 10,
        rewardTitle: 'مشروب توقيع + حلوى مجانية',
        rewardTitleEn: 'Signature Drink + Artisanal Dessert',
        rewardDescription: 'المكافأة الكبرى: مشروب من اختيارك مع قطعة حلوى',
        icon: 'crown',
        discountPercent: 100,
        codePrefix: 'ESP-GRAND',
        isGrandPrize: true,
      },
    ],
    theme: {
      id: 'theme_espresso_leather',
      nameEn: 'Dark Matte Leather & Bronze Foil',
      nameAr: 'جلد غير لامع ورقائق برونزية',
      background: 'linear-gradient(135deg, #1C130E 0%, #2A1D15 50%, #150E0A 100%)',
      textColor: '#FDFBF7',
      secondaryTextColor: '#C5A880',
      accentColor: '#D4AF37',
      borderColor: '#3D2A1F',
      stampBorderColor: '#8C683A',
      stampActiveBg: 'radial-gradient(circle, #D4AF37 0%, #A67C2E 70%, #6E4E18 100%)',
      stampActiveColor: '#1A1108',
      stampInactiveBg: 'rgba(255, 255, 255, 0.04)',
      stampInactiveColor: '#8C683A',
      texture: 'leather',
      foilEffect: 'bronze',
      fontFamily: 'cairo',
      glowColor: 'rgba(212, 175, 55, 0.35)',
      badgeBg: 'linear-gradient(90deg, #A67C2E 0%, #D4AF37 50%, #A67C2E 100%)',
      badgeTextColor: '#150E0A',
    },
  },

  minimal_kraft: {
    id: 'minimal_kraft',
    nameEn: 'Minimal Kraft',
    nameAr: 'كرافت بيئي & حبر مطاطي',
    description: 'Eco-friendly recycled kraft paper aesthetic with tactile rubber stamp impressions and vintage typewriter accents.',
    descriptionAr: 'ورق كرافت بيئي معاد تدويره مع أختام الحبر المطاطي الكلاسيكي وخطوط الآلة الكاتبة الدافئة.',
    dimensionType: 'square',
    dimensions: LOYALTY_DIMENSIONS.square,
    slotCount: 8,
    badgeText: 'ECO CLUB',
    badgeTextAr: 'نادي الاستدامة',
    tagline: 'Artisanal Coffee & Good Vibes',
    taglineAr: 'قهوة حرفية وتجارب أصيلة',
    termsAndConditions: [
      'Each stamped slot represents one handcrafted memory.',
      'Cannot be exchanged for cash.',
      'Show QR to barista when placing an order.',
    ],
    termsAndConditionsAr: [
      'كل ختم يمثل زيارة وذكرى حقيقية في الكافيه.',
      'المكافآت غير قابلة للتحويل إلى مبالغ نقدية.',
      'أظهر كود الـ QR عند كاونتر الطلبات.',
    ],
    milestones: [
      {
        slot: 4,
        rewardTitle: 'خصم 50% على أي مشروب',
        rewardTitleEn: '50% Off Any Beverage',
        rewardDescription: 'نصف السعر لمشروبك المفضل في منتصف الرحلة',
        icon: 'tag',
        discountPercent: 50,
        codePrefix: 'KRAFT-HALF',
        isGrandPrize: false,
      },
      {
        slot: 8,
        rewardTitle: 'مشروبك المفضل مجاناً',
        rewardTitleEn: 'Free Favorite Coffee',
        rewardDescription: 'مشروب مجاني بالكامل مع طباعة ذكرى إضافية',
        icon: 'gift',
        discountPercent: 100,
        codePrefix: 'KRAFT-FREE',
        isGrandPrize: true,
      },
    ],
    theme: {
      id: 'theme_minimal_kraft',
      nameEn: 'Warm Kraft & Indigo Ink',
      nameAr: 'ورق كرافت وحبر نيلي',
      background: 'linear-gradient(135deg, #EFE4D2 0%, #E3D3BE 50%, #D5BF9E 100%)',
      textColor: '#2E2218',
      secondaryTextColor: '#70533C',
      accentColor: '#1F2937',
      borderColor: '#CBB294',
      stampBorderColor: '#8C6C4E',
      stampActiveBg: 'radial-gradient(circle, #2A3B4C 0%, #1A2530 100%)',
      stampActiveColor: '#EFE4D2',
      stampInactiveBg: 'rgba(255, 255, 255, 0.45)',
      stampInactiveColor: '#9C7A58',
      texture: 'kraft',
      foilEffect: 'none',
      fontFamily: 'tajawal',
      glowColor: 'rgba(42, 59, 76, 0.2)',
      badgeBg: '#2E2218',
      badgeTextColor: '#EFE4D2',
    },
  },

  neon_cyber_latte: {
    id: 'neon_cyber_latte',
    nameEn: 'Neon Cyber Latte',
    nameAr: 'نيون سايبر لاتيه (دارك مود)',
    description: 'Ultra-modern dark interface with vibrant glowing neon rings, cybernetic grid lines, and iridescent badges.',
    descriptionAr: 'تصميم داكن مستقبلي بحلقات نيون متوهجة وشبكة سايبر وجاذبية تكنولوجية فائقة السرعة.',
    dimensionType: 'wallet',
    dimensions: LOYALTY_DIMENSIONS.wallet,
    slotCount: 6,
    badgeText: 'CYBER PASSPORT',
    badgeTextAr: 'جواز السايبر الذكي',
    tagline: 'High Octane Caffeine Experience',
    taglineAr: 'تجربة كافيين رقمية فائقة السرعة',
    termsAndConditions: [
      'Flash QR code on terminal scanner.',
      'Cyber tokens unlock high priority cafe perks.',
      'Instant cloud sync across devices.',
    ],
    termsAndConditionsAr: [
      'امسح رمز الـ QR على شاشة الكاشير السريعة.',
      'تمنحك الأختام مزايا حصرية وخصومات فورية.',
      'مزامنة سحابية فورية مع سجل زياراتك.',
    ],
    milestones: [
      {
        slot: 3,
        rewardTitle: 'ترقية مجانية للحجم الكبير',
        rewardTitleEn: 'Free Size Upgrade (Large)',
        rewardDescription: 'ترقية مجانية فورية لأي مشروب بحجم أكبر',
        icon: 'sparkles',
        discountPercent: 30,
        codePrefix: 'CYBER-UP',
        isGrandPrize: false,
      },
      {
        slot: 6,
        rewardTitle: 'مشروب نيون كولد برو مجاناً',
        rewardTitleEn: 'Free Signature Neon Cold Brew',
        rewardDescription: 'مشروب كولد برو خاص من قائمة السايبر مجاناً',
        icon: 'crown',
        discountPercent: 100,
        codePrefix: 'CYBER-FREE',
        isGrandPrize: true,
      },
    ],
    theme: {
      id: 'theme_neon_cyber',
      nameEn: 'Obsidian & Cyan Neon Pulse',
      nameAr: 'أوبسيديان ونيون سيان مشع',
      background: 'linear-gradient(135deg, #090D16 0%, #0F172A 60%, #05070B 100%)',
      textColor: '#F8FAFC',
      secondaryTextColor: '#38BDF8',
      accentColor: '#00F2FE',
      borderColor: 'rgba(0, 242, 254, 0.3)',
      stampBorderColor: '#00F2FE',
      stampActiveBg: 'radial-gradient(circle, #00F2FE 0%, #0284C7 80%, #0369A1 100%)',
      stampActiveColor: '#020617',
      stampInactiveBg: 'rgba(15, 23, 42, 0.7)',
      stampInactiveColor: '#0284C7',
      texture: 'neon',
      foilEffect: 'neon',
      fontFamily: 'sans',
      glowColor: 'rgba(0, 242, 254, 0.65)',
      badgeBg: 'linear-gradient(90deg, #00F2FE 0%, #38BDF8 50%, #818CF8 100%)',
      badgeTextColor: '#020617',
    },
  },

  botanical_matcha: {
    id: 'botanical_matcha',
    nameEn: 'Botanical Matcha',
    nameAr: 'ماتشا بوتانيكال & زهر البن',
    description: 'Serene organic sage green palette with floral coffee blossom filigree, calming vibes, and satin gold leaf finishes.',
    descriptionAr: 'درجات الماتشا والميرمية الناعمة مع زخارف زهر البن وأوراق الذهب الساتان لمقاهي الطبيعة والراحة.',
    dimensionType: 'wallet',
    dimensions: LOYALTY_DIMENSIONS.wallet,
    slotCount: 8,
    badgeText: 'GREEN SANCTUARY',
    badgeTextAr: 'نادي الماتشا والطبيعة',
    tagline: 'Organic Tea & Botanical Brews',
    taglineAr: 'شاي عضوي ونفحات طبيعية منعشة',
    termsAndConditions: [
      'One leaf stamp per beverage purchase.',
      'Show card to server or barista upon checkout.',
      'Valid at all botanical lounge locations.',
    ],
    termsAndConditionsAr: [
      'ختم ورقة ماتشا مع كل مشروب أو حلوى عضوية.',
      'أبرز الرمز للباريستا عند استلام طلبك.',
      'سارية في جميع فروع المقهى الطبيعي.',
    ],
    milestones: [
      {
        slot: 4,
        rewardTitle: 'قطعة كوكيز ماتشا مجانية',
        rewardTitleEn: 'Free Artisanal Matcha Cookie',
        rewardDescription: 'قطعة بسكويت طازجة محضرة بأجود أنواع الماتشا',
        icon: 'cookie',
        discountPercent: 100,
        codePrefix: 'MATCHA-COOKIE',
        isGrandPrize: false,
      },
      {
        slot: 8,
        rewardTitle: 'ماتشا لاتيه فاخرة مجاناً',
        rewardTitleEn: 'Ceremonial Grade Matcha Latte',
        rewardDescription: 'كوب ماتشا احتفالية مجانية بالحليب النباتي من اختيارك',
        icon: 'crown',
        discountPercent: 100,
        codePrefix: 'MATCHA-GRAND',
        isGrandPrize: true,
      },
    ],
    theme: {
      id: 'theme_botanical_matcha',
      nameEn: 'Sage Green & Satin Gold',
      nameAr: 'أخضر ميرمية وذهب ساتان',
      background: 'linear-gradient(135deg, #EDF3ED 0%, #D8E6D8 50%, #CADCC9 100%)',
      textColor: '#1B3523',
      secondaryTextColor: '#3E6549',
      accentColor: '#B8860B',
      borderColor: '#ADC4AE',
      stampBorderColor: '#3E6549',
      stampActiveBg: 'radial-gradient(circle, #2E5238 0%, #1E3A25 100%)',
      stampActiveColor: '#E2EFE2',
      stampInactiveBg: 'rgba(255, 255, 255, 0.55)',
      stampInactiveColor: '#6B8E6F',
      texture: 'botanical',
      foilEffect: 'gold',
      fontFamily: 'cairo',
      glowColor: 'rgba(46, 82, 56, 0.25)',
      badgeBg: '#1B3523',
      badgeTextColor: '#EDF3ED',
    },
  },

  photobooth_strip: {
    id: 'photobooth_strip',
    nameEn: 'Photobooth Memories Strip',
    nameAr: 'شريط الذكريات (كشك التصوير)',
    description: 'Vertical 4-cut photobooth memory strip. Every visit becomes an actual photo stamp along the strip.',
    descriptionAr: 'شريط تصوير رأسي يحول كل زيارة إلى لقطة وصورة حقيقية ضمن بطاقة الذكريات.',
    dimensionType: 'strip',
    dimensions: LOYALTY_DIMENSIONS.strip,
    slotCount: 4,
    badgeText: 'PHOTO PASS',
    badgeTextAr: 'شريط الذكريات',
    tagline: 'Snap, Sip & Collect',
    taglineAr: 'صوّر، اشرب، واجمع لحظاتك',
    termsAndConditions: [
      'Photos taken in the booth are printed and stamped here.',
      'Unlock a complimentary framed print and drink on completion.',
    ],
    termsAndConditionsAr: [
      'تضاف صور كابينة التصوير كأختام فورية على الشريط.',
      'اكتمال الشريط يمنحك طباعة هدية مجانية ومشروباً خاصاً.',
    ],
    milestones: [
      {
        slot: 2,
        rewardTitle: 'إضافة ستيكرات وطباعة ثانية مجانية',
        rewardTitleEn: 'Free Sticker Pack + Extra Print',
        rewardDescription: 'طباعة صورة إضافية مجاناً مع باقة ملصقات كورية',
        icon: 'sparkles',
        discountPercent: 50,
        codePrefix: 'STRIP-STICKER',
        isGrandPrize: false,
      },
      {
        slot: 4,
        rewardTitle: 'شريط صور مؤطر + مشروب مجاني',
        rewardTitleEn: 'Framed Strip + Signature Drink',
        rewardDescription: 'إطار خشبي لصور ذكرياتك الأربع مع مشروبك المفضل مجاناً',
        icon: 'gift',
        discountPercent: 100,
        codePrefix: 'STRIP-GRAND',
        isGrandPrize: true,
      },
    ],
    theme: {
      id: 'theme_photobooth_strip',
      nameEn: 'Warm Cream & Vintage Ink',
      nameAr: 'كريمي دافئ وحبر كلاسيكي',
      background: 'linear-gradient(180deg, #FBF8F2 0%, #F5EDE0 100%)',
      textColor: '#1E1B18',
      secondaryTextColor: '#826B54',
      accentColor: '#D97706',
      borderColor: '#E2D5C3',
      stampBorderColor: '#826B54',
      stampActiveBg: '#1E1B18',
      stampActiveColor: '#FBF8F2',
      stampInactiveBg: 'rgba(255, 255, 255, 0.8)',
      stampInactiveColor: '#B09880',
      texture: 'matte',
      foilEffect: 'none',
      fontFamily: 'tajawal',
      glowColor: 'rgba(217, 119, 6, 0.25)',
      badgeBg: '#1E1B18',
      badgeTextColor: '#FBF8F2',
    },
  },
};

export const DEFAULT_LOYALTY_TEMPLATE: LoyaltyCardTemplate = LOYALTY_CARD_PRESETS.espresso_pass;

/**
 * Retrieve preset by id with fallback to default
 */
export function getLoyaltyTemplateById(id: string): LoyaltyCardTemplate {
  return LOYALTY_CARD_PRESETS[id] || DEFAULT_LOYALTY_TEMPLATE;
}
