import { BusinessSettings, CustomerPersonaInfo, PhotoboothFrame, PhotoboothFrameTemplate, PhotoboothCardMode } from '@/types/photobooth';

export const CUSTOMER_PERSONAS: CustomerPersonaInfo[] = [
  {
    key: 'tech_freelancer',
    label: 'تقني / فريلانسر',
    icon: '💻',
    badgeColor: 'bg-blue-50 text-blue-800 border-blue-200',
  },
  {
    key: 'creator_creative',
    label: 'صانع محتوى / مبدع',
    icon: '🎨',
    badgeColor: 'bg-pink-50 text-pink-800 border-pink-200',
  },
  {
    key: 'student_researcher',
    label: 'طالب / باحث',
    icon: '🎓',
    badgeColor: 'bg-amber-50 text-amber-800 border-amber-200',
  },
  {
    key: 'business_founder',
    label: 'أعمال / ريادة',
    icon: '💼',
    badgeColor: 'bg-emerald-50 text-emerald-800 border-emerald-200',
  },
  {
    key: 'coffee_lover',
    label: 'زائر ومحب للقهوة',
    icon: '☕',
    badgeColor: 'bg-stone-100 text-stone-800 border-stone-300',
  },
  {
    key: 'other',
    label: 'تصنيف آخر',
    icon: '✨',
    badgeColor: 'bg-purple-50 text-purple-800 border-purple-200',
  },
];

export const PRESET_COLOR_PALETTES: {
  id: string;
  nameAr: string;
  bgColor: string;
  borderColor: string;
  textColor: string;
  accentColor: string;
}[] = [
  {
    id: 'classic-latte',
    nameAr: '☕ كافيه لاتيه كلاسيك',
    bgColor: '#F5F0EB',
    borderColor: '#E6DCCF',
    textColor: '#2A1810',
    accentColor: '#C67D34',
  },
  {
    id: 'noir-korean',
    nameAr: '🖤 أسود نوار فخم',
    bgColor: '#18181B',
    borderColor: '#27272A',
    textColor: '#FAFAFA',
    accentColor: '#A1A1AA',
  },
  {
    id: 'warm-amber',
    nameAr: '🍯 عنبر القهوة الدافئ',
    bgColor: '#FFFBEB',
    borderColor: '#FDE68A',
    textColor: '#78350F',
    accentColor: '#B45309',
  },
  {
    id: 'terracotta-clay',
    nameAr: '🧱 طمي وتيراكوتا',
    bgColor: '#FAF5F0',
    borderColor: '#E2C4B1',
    textColor: '#431407',
    accentColor: '#C2410C',
  },
  {
    id: 'olive-garden',
    nameAr: '🌿 زيتوني هادئ وطبيعي',
    bgColor: '#F4F6F0',
    borderColor: '#D5DDD0',
    textColor: '#1C2818',
    accentColor: '#4D7C0F',
  },
  {
    id: 'sakura-blush',
    nameAr: '🌸 وردي ساكورا ناعم',
    bgColor: '#FFF0F3',
    borderColor: '#FFCCD5',
    textColor: '#591C2B',
    accentColor: '#E11D48',
  },
  {
    id: 'ivory-cream',
    nameAr: '🤍 عاجي كريمي نقي',
    bgColor: '#FAF8F5',
    borderColor: '#E7E2D9',
    textColor: '#1C1917',
    accentColor: '#D97706',
  },
];

export const DEFAULT_PHOTOBOOTH_FRAMES: PhotoboothFrame[] = [
  {
    id: 'classic-latte',
    name: 'Classic Latte',
    nameAr: 'كافيه لاتيه كلاسيك',
    bgColor: '#F5F0EB',
    textColor: '#2A1810',
    borderColor: '#E6DCCF',
    accentColor: '#C67D34',
    cornerEmojis: {
      topRight: '☕',
      bottomLeft: '✨',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 3,
    frameShape: 'rounded',
    badgeText: 'MEMORIES STUDIO',
    isCustom: false,
  },
  {
    id: 'noir-korean',
    name: 'Korean Noir',
    nameAr: 'كوريان نوار فخم',
    bgColor: '#18181B',
    textColor: '#FAFAFA',
    borderColor: '#27272A',
    accentColor: '#A1A1AA',
    cornerEmojis: {
      topRight: '⚡',
      bottomLeft: '🖤',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 3,
    frameShape: 'rounded',
    badgeText: 'SEOUL 4-CUTS',
    isCustom: false,
  },
  {
    id: 'warm-amber',
    name: 'Warm Amber',
    nameAr: 'عنبر القهوة المختصة',
    bgColor: '#FFFBEB',
    textColor: '#78350F',
    borderColor: '#FDE68A',
    accentColor: '#B45309',
    cornerEmojis: {
      topRight: '☕',
      bottomLeft: '🥐',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 3,
    frameShape: 'rounded',
    badgeText: 'SPECIALTY ROASTERS',
    isCustom: false,
  },
  {
    id: 'ivory-cream',
    name: 'Ivory Cream',
    nameAr: 'العاجي الفاخر',
    bgColor: '#FAF8F5',
    textColor: '#1C1917',
    borderColor: '#E7E2D9',
    accentColor: '#D97706',
    cornerEmojis: {
      topRight: '✨',
      bottomLeft: '🎞️',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 3,
    frameShape: 'rounded',
    badgeText: 'MEMORIES STUDIO',
    isCustom: false,
  },
  {
    id: 'terracotta-clay',
    name: 'Terracotta',
    nameAr: 'طمي وتيراكوتا',
    bgColor: '#FAF5F0',
    textColor: '#431407',
    borderColor: '#E2C4B1',
    accentColor: '#C2410C',
    cornerEmojis: {
      topRight: '🧱',
      bottomLeft: '🏺',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 3,
    frameShape: 'rounded',
    badgeText: 'TERRACOTTA WARMTH',
    isCustom: false,
  },
];

export const DEFAULT_BUSINESS_SETTINGS: BusinessSettings = {
  cafeSlug: 'espresso-lab',
  cafeName: 'Memories • إكسبرسو لاب',
  branding: {
    name: 'Memories Studio',
    logoUrl: '',
    tagline: 'لحظات لا تُنسى في كل زيارة',
  },
  defaultShotCount: 3,
  defaultOrientation: 'vertical',
  defaultFrameShape: 'rounded',
  defaultCardMode: 'korean_noir',
  freeGiftOffer: {
    title: 'مشروب مجاني أو هدية فورية',
    subtitle: 'أظهر هذا الشريط للباريستا لاستلام هديتك مع الصورة المطبوعة',
    icon: '🎁',
  },
  activeFrameId: 'classic-latte',
  activeColorPaletteId: 'classic-latte',
  allowCustomerColorChoice: true,
  allowedColorIds: ['classic-latte', 'noir-korean', 'warm-amber', 'ivory-cream', 'terracotta-clay'],
  allowCustomerStickers: true,
  allowCustomerModeChoice: true,
  allowedModes: ['korean_noir', 'cafe_latte', 'retro_film', 'sakura_y2k', 'polaroid_classic'],
  frames: DEFAULT_PHOTOBOOTH_FRAMES,
};

export const PRESET_EMOJI_PAIRS = [
  { label: 'نجوم ولقطات', topRight: '✨', bottomLeft: '🎞️' },
  { label: 'ساكورا وقلب', topRight: '🌸', bottomLeft: '💖' },
  { label: 'قهوة وكرواسون', topRight: '☕', bottomLeft: '🥐' },
  { label: 'طاقة ونوار', topRight: '⚡', bottomLeft: '🖤' },
  { label: 'شريطة وكاميرا', topRight: '🎀', bottomLeft: '📸' },
  { label: 'كرز وفراشة', topRight: '🍒', bottomLeft: '🦋' },
  { label: 'دبدوب وعسل', topRight: '🧸', bottomLeft: '🍯' },
  { label: 'كأس وتاج', topRight: '👑', bottomLeft: '🥂' },
];

export interface PhotoboothModeInfo {
  id: PhotoboothCardMode;
  nameAr: string;
  nameEn: string;
  icon: string;
  description: string;
  defaultBg: string;
  defaultBorder: string;
  defaultText: string;
  defaultAccent: string;
  filmBadge: string;
  widthCm?: number;
  heightCm?: number;
}

export const PHOTOBOOTH_CARD_MODES: PhotoboothModeInfo[] = [
  {
    id: 'korean_noir',
    nameAr: 'نوار كوري فخم (Seoul Studio)',
    nameEn: 'Korean Noir 4-Cuts',
    icon: '✦',
    description: 'أسود نوار غير لامع، تايبوغرافي استوديو سول العصري مع باركود وأرقام كلاسيكية',
    defaultBg: '#121214',
    defaultBorder: '#222226',
    defaultText: '#F4F4F5',
    defaultAccent: '#71717A',
    filmBadge: 'SEOUL 4-CUTS // 35MM ISO 400',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'cafe_latte',
    nameAr: 'كافيه روستري بورسلين (Specialty)',
    nameEn: 'Cafe Specialty Roastery',
    icon: '✦',
    description: 'ورق بورسلين كريمي دافئ ملمسي، ترويسة روستري الحرفية، ونصوص بلون الإسبريسو',
    defaultBg: '#FAF6F0',
    defaultBorder: '#EADFD3',
    defaultText: '#2B1810',
    defaultAccent: '#B46B34',
    filmBadge: 'SPECIALTY ROASTERS // SINGLE ORIGIN',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'wide_duo_2cut',
    nameAr: 'الكارت العريض القصير (صورتين جنب بعض)',
    nameEn: 'Wide Duo Postcard',
    icon: '✦',
    description: 'كارت عريض وقصير متوازن ومريح؛ صورتان أفقيتان جنباً إلى جنب بهوامش استوديو ناعمة',
    defaultBg: '#FBF9F5',
    defaultBorder: '#E8E2D8',
    defaultText: '#1A1A1A',
    defaultAccent: '#C2410C',
    filmBadge: 'MEMORIES POSTCARD // EDITION 02',
    widthCm: 10,
    heightCm: 7.6,
  },
  {
    id: 'retro_film',
    nameAr: 'فيلم 35mm ريترو سينمائي (Sprocket Holes)',
    nameEn: 'Retro 35mm Analog Film',
    icon: '✦',
    description: 'طابع شرائط الأفلام التناظرية مع ثقوب التروس الجانبية وعلامات الكوداك والـ 35 مم',
    defaultBg: '#1C1917',
    defaultBorder: '#292524',
    defaultText: '#FEF08A',
    defaultAccent: '#F97316',
    filmBadge: 'KODAK SAFETY FILM 400 // DX CODE',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'kinfolk_minimal',
    nameAr: 'كينفولك مينيمال نقي (Gallery White)',
    nameEn: 'Kinfolk Minimalist',
    icon: '✦',
    description: 'أبيض ناصع مع خطوط رفيعة جداً ومساحات تنفس واسعة بأسلوب المجلات المعمارية',
    defaultBg: '#FFFFFF',
    defaultBorder: '#E5E5E5',
    defaultText: '#111111',
    defaultAccent: '#999999',
    filmBadge: 'KINFOLK EDITION // ARCHITECTURAL',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'polaroid_classic',
    nameAr: 'بولارويد كلاسيكي أصلي (Wide Chin)',
    nameEn: 'Classic Polaroid',
    icon: '✦',
    description: 'إطار الكاميرا الفورية المربع مع الحافة السفلية العريضة الشهيرة لكتابة التاريخ أو التوقيع',
    defaultBg: '#F8F6F0',
    defaultBorder: '#E6E2D6',
    defaultText: '#374151',
    defaultAccent: '#D97706',
    filmBadge: 'ORIGINAL INSTANT PRINT // 600 FILM',
    widthCm: 8.8,
    heightCm: 10.7,
  },
  {
    id: 'tokyo_pastel',
    nameAr: 'طوكيو باستيل بوب (Refined Sakura)',
    nameEn: 'Tokyo Pastel Pop',
    icon: '✦',
    description: 'وردي ساكورا هادئ وراقٍ مع لمسات يابانية ناعمة وتصميم عصري غير مبتذل',
    defaultBg: '#FDF2F4',
    defaultBorder: '#FBCFE8',
    defaultText: '#831843',
    defaultAccent: '#F43F5E',
    filmBadge: 'メモリー・スタジオ // TOKYO EDITION',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'cinema_horizontal',
    nameAr: 'شريط سينمائي 16:9 بانورامي',
    nameEn: 'Cinema Widescreen',
    icon: '✦',
    description: '3 كادرات عريضة بنسبة 16:9 بأسلوب لقطات الأفلام السينمائية مع ترويسة رقم المشهد',
    defaultBg: '#09090B',
    defaultBorder: '#18181B',
    defaultText: '#E4E4E7',
    defaultAccent: '#EAB308',
    filmBadge: 'CINEMA SCOPE 2.39:1 // SCENE 01',
    widthCm: 15.2,
    heightCm: 5,
  },
  {
    id: 'arabica_monochrome',
    nameAr: '% أرابيكا مونوكروم استوديو',
    nameEn: '% Arabica Monochrome',
    icon: '✦',
    description: 'تصميم هندسي فائق النقاء بالأبيض والأسود مع تايبوغرافي قوي مستوحى من المقاهي اليابانية',
    defaultBg: '#FFFFFF',
    defaultBorder: '#000000',
    defaultText: '#000000',
    defaultAccent: '#737373',
    filmBadge: '% MEMORIES // KYOTO DESIGN',
    widthCm: 5,
    heightCm: 15.2,
  },
];

export const CURATED_STICKER_SET = [
  '✦', '☕', '🖤', '🤍', '🥐', '✨', '📸', '🎞️',
  '🌿', '💫', '💌', '🌸', '🍵', '⚡', '🌙', '🪐',
];

export const PHOTOBOOTH_FRAME_TEMPLATES: PhotoboothFrameTemplate[] = [
  {
    id: 'korean_noir_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: 'Korean Noir Strip (4 Cuts)',
    nameAr: 'الشريط الكوري الأسود (4 لقطات - Seoul Studio)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 4,
    layoutType: 'strip_4',
    description: 'الأكثر شهرة على بنترست وفي استوديوهات سول؛ 4 صور رأسية أنيقة بحدود بيضاء رقيقة وتاريخ نقطي وباركود',
    badge: 'SEOUL 4-CUTS',
    icon: '✦',
    defaultBg: '#121214',
    defaultBorder: '#222226',
    defaultText: '#F4F4F5',
    defaultAccent: '#71717A',
  },
  {
    id: 'classic_latte_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: 'Café Specialty Roastery (3 Cuts)',
    nameAr: 'كافيه سبيشالتي روستري (3 لقطات - بورسلين دافئ)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 3,
    layoutType: 'strip_3',
    description: '3 صور عريضة مريحة للعين بلون ورق البورسلين الدافئ وخط أنيق باسم الروستري ونجمة ذهبية',
    badge: 'SPECIALTY ROASTERS',
    icon: '✦',
    defaultBg: '#FAF6F0',
    defaultBorder: '#EADFD3',
    defaultText: '#2B1810',
    defaultAccent: '#B46B34',
  },
  {
    id: 'wide_duo_2cut',
    widthCm: 10,
    heightCm: 7.6,
    nameEn: 'Wide Duo (2 Side-by-Side)',
    nameAr: 'الكارت العريض القصير (صورتين جنب بعض - 10×7.6 سم)',
    dimensions: '4x3 in',
    dimensionsCm: '10 × 7.6 سم',
    orientation: 'horizontal',
    shotCount: 2,
    layoutType: 'wide_duo_2cut',
    description: 'كارت عريض وقصير مريح جداً؛ صورتان أفقيتان جنباً إلى جنب بهوامش استوديو ناعمة ومظهر أنيق ومتوازن',
    badge: 'WIDE DUO 2',
    icon: '✦',
    defaultBg: '#FBF9F5',
    defaultBorder: '#E8E2D8',
    defaultText: '#1A1A1A',
    defaultAccent: '#C2410C',
  },
  {
    id: 'wide_duo_4cut',
    widthCm: 10,
    heightCm: 8.8,
    nameEn: 'Compact Duo (2x2 Side-by-Side)',
    nameAr: 'كارت عريض مدمج 2×2 (4 صور - 10×8.8 سم)',
    dimensions: '4x3.5 in',
    dimensionsCm: '10 × 8.8 سم',
    orientation: 'horizontal',
    shotCount: 4,
    layoutType: 'wide_duo_4cut',
    description: 'كارت عريض مدمج؛ 4 كادرات مصفوفة في شبكة 2×2 متناسقة لتوثيق اللحظة بشكل مضغوط وجميل',
    badge: 'COMPACT 2x2',
    icon: '✦',
    defaultBg: '#F5F4F0',
    defaultBorder: '#E2E0D8',
    defaultText: '#262626',
    defaultAccent: '#8C7853',
  },
  {
    id: 'kinfolk_minimal_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: 'Kinfolk Minimalist (3 Cuts)',
    nameAr: 'كينفولك مينيمال نقي (3 لقطات - Gallery White)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 3,
    layoutType: 'kinfolk_minimal',
    description: '3 لقطات بهوامش واسعة جداً وتصميم نقي باللون الأبيض الحليبي مع خطوط هيرلاين دقيقة جداً',
    badge: 'KINFOLK EDITION',
    icon: '✦',
    defaultBg: '#FFFFFF',
    defaultBorder: '#E5E5E5',
    defaultText: '#111111',
    defaultAccent: '#999999',
  },
  {
    id: 'retro_film_35mm',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: 'Analog 35mm Film (4 Cuts)',
    nameAr: 'شريط نيجاتيف 35 مم ريترو (4 لقطات - Sprockets)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 4,
    layoutType: 'film_35mm',
    description: 'شريط فيلم كوداك حقيقي مع ثقوب التروس الجانبية وأرقام الكادرات الفيلمية والباركود التناظري',
    badge: 'KODAK 400TX',
    icon: '✦',
    defaultBg: '#1C1917',
    defaultBorder: '#292524',
    defaultText: '#FEF08A',
    defaultAccent: '#F97316',
  },
  {
    id: 'polaroid_classic',
    widthCm: 8.8,
    heightCm: 10.7,
    nameEn: 'Polaroid 600 Square (1 Cut)',
    nameAr: 'بولارويد كلاسيكي مربع (لقطة واحدة - Wide Chin)',
    dimensions: '3.5x4.2 in',
    dimensionsCm: '8.8 × 10.7 سم',
    orientation: 'vertical',
    shotCount: 1,
    layoutType: 'polaroid_square',
    description: 'الإطار الأيقوني لكاميرات البولارويد؛ صورة مربعة 1:1 مع ذقن أبيض عريض لكتابة التوقيع أو التاريخ',
    badge: 'POLAROID 600',
    icon: '✦',
    defaultBg: '#F8F6F0',
    defaultBorder: '#E6E2D6',
    defaultText: '#374151',
    defaultAccent: '#D97706',
  },
  {
    id: 'tokyo_pastel_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: 'Tokyo Pastel Pop (4 Cuts)',
    nameAr: 'طوكيو باستيل بوب (4 لقطات - ساكورا راقية)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 4,
    layoutType: 'strip_4',
    description: 'درجات الوردي الباستيل الهادئ مع كتابة يابانية أنيقة وحواف ناعمة بأسلوب استوديوهات طوكيو',
    badge: 'TOKYO EDITION',
    icon: '✦',
    defaultBg: '#FDF2F4',
    defaultBorder: '#FBCFE8',
    defaultText: '#831843',
    defaultAccent: '#F43F5E',
  },
  {
    id: 'cinema_strip_6x2',
    widthCm: 15.2,
    heightCm: 5,
    nameEn: 'Cinema Trio 16:9 (3 Cuts)',
    nameAr: 'الشريط السينمائي البانورامي (3 لقطات - 16:9)',
    dimensions: '6x2 in',
    dimensionsCm: '15.2 × 5 سم',
    orientation: 'horizontal',
    shotCount: 3,
    layoutType: 'cinema_horizontal',
    description: '3 كادرات سينمائية عريضة 16:9 جنباً إلى جنب مع أشرطة لقطات الأفلام وشريط ترجمة وهمي',
    badge: 'CINEMA SCOPE',
    icon: '✦',
    defaultBg: '#09090B',
    defaultBorder: '#18181B',
    defaultText: '#E4E4E7',
    defaultAccent: '#EAB308',
  },
  {
    id: 'arabica_monochrome_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: '% Arabica Monochrome (3 Cuts)',
    nameAr: '% أرابيكا مونوكروم (3 لقطات - كيوتو ديزاين)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 3,
    layoutType: 'arabica_monochrome',
    description: 'تصميم هندسي فائق النقاء بالأبيض والأسود مع تايبوغرافي قوي مستوحى من أرابيكا كيوتو',
    badge: '% ARABICA KYOTO',
    icon: '✦',
    defaultBg: '#FFFFFF',
    defaultBorder: '#000000',
    defaultText: '#000000',
    defaultAccent: '#737373',
  },
];

