import {
  BusinessSettings,
  CustomerPersonaInfo,
  PhotoboothFrame,
  PhotoboothFrameTemplate,
  PhotoboothCardMode,
  StripOrientation,
} from '@/types/photobooth';

export const CUSTOMER_PERSONAS: CustomerPersonaInfo[] = [
  {
    key: 'tech_freelancer',
    label: 'تقني / فريلانسر',
    icon: 'tech',
    badgeColor: 'bg-blue-50 text-blue-800 border-blue-200',
  },
  {
    key: 'creator_creative',
    label: 'صانع محتوى / مبدع',
    icon: 'creative',
    badgeColor: 'bg-pink-50 text-pink-800 border-pink-200',
  },
  {
    key: 'student_researcher',
    label: 'طالب / باحث',
    icon: 'student',
    badgeColor: 'bg-amber-50 text-amber-800 border-amber-200',
  },
  {
    key: 'business_founder',
    label: 'أعمال / ريادة',
    icon: 'business',
    badgeColor: 'bg-emerald-50 text-emerald-800 border-emerald-200',
  },
  {
    key: 'coffee_lover',
    label: 'زائر ومحب للقهوة',
    icon: 'coffee',
    badgeColor: 'bg-stone-100 text-stone-800 border-stone-300',
  },
  {
    key: 'other',
    label: 'تصنيف آخر',
    icon: 'general',
    badgeColor: 'bg-purple-50 text-purple-800 border-purple-200',
  },
];

export const PRESET_COLOR_PALETTES: {
  id: string;
  nameAr: string;
  bgColor: string;
  borderColor: string;
  textColor: string;
  accentColor: string;
}[] = [
  {
    id: 'ticket-express-cream',
    nameAr: 'تذكرة القطار الكلاسيكية (The Snap Express)',
    bgColor: '#FAF5EC',
    borderColor: '#4A121A',
    textColor: '#3D1016',
    accentColor: '#8B2635',
  },
  {
    id: 'spotify-slate-blue',
    nameAr: 'سبوتيفاي أزرق حجري (Slate Blue)',
    bgColor: '#384C5A',
    borderColor: '#26343E',
    textColor: '#FFFFFF',
    accentColor: '#1DB954',
  },
  {
    id: 'spotify-warm-taupe',
    nameAr: 'سبوتيفاي زيتي كافيه (Warm Taupe)',
    bgColor: '#4E483E',
    borderColor: '#37322B',
    textColor: '#FFFFFF',
    accentColor: '#1DB954',
  },
  {
    id: 'spotify-charcoal-oled',
    nameAr: 'سبوتيفاي أسود داكن (Charcoal Dark)',
    bgColor: '#161618',
    borderColor: '#28282B',
    textColor: '#FFFFFF',
    accentColor: '#1DB954',
  },
  {
    id: 'spotify-burnt-terracotta',
    nameAr: 'سبوتيفاي تيراكوتا (Burnt Terracotta)',
    bgColor: '#8B3A2B',
    borderColor: '#67281D',
    textColor: '#FFFFFF',
    accentColor: '#1DB954',
  },
  {
    id: 'ios-clean-white',
    nameAr: 'آبل صور نهاري (iOS Light)',
    bgColor: '#F2F2F7',
    borderColor: '#D1D1D6',
    textColor: '#000000',
    accentColor: '#007AFF',
  },
  {
    id: 'ios-oled-black',
    nameAr: 'آبل شاشات سوداء (iOS OLED Dark)',
    bgColor: '#000000',
    borderColor: '#1C1C1E',
    textColor: '#FFFFFF',
    accentColor: '#0A84FF',
  },
  {
    id: 'memories-signature',
    nameAr: 'هوية ميموريز الرسمية (Artisanal Coffee)',
    bgColor: '#E8DCC6',
    borderColor: '#3B2F2A',
    textColor: '#3B2F2A',
    accentColor: '#B85C43',
  },
  {
    id: 'memories-forest',
    nameAr: 'ميموريز فورست جرين (Deep Forest)',
    bgColor: '#1E3A32',
    borderColor: '#2A4F44',
    textColor: '#FAF6EE',
    accentColor: '#B85C43',
  },
  {
    id: 'classic-latte',
    nameAr: 'كافيه لاتيه كلاسيك',
    bgColor: '#F5F0EB',
    borderColor: '#E6DCCF',
    textColor: '#2A1810',
    accentColor: '#C67D34',
  },
  {
    id: 'noir-korean',
    nameAr: 'أسود نوار فخم (Seoul)',
    bgColor: '#121214',
    borderColor: '#27272A',
    textColor: '#F4F4F5',
    accentColor: '#A1A1AA',
  },
  {
    id: 'arabica-gold',
    nameAr: 'أرابيكا ذهبي فاخر (Espresso & Gold)',
    bgColor: '#14110F',
    borderColor: '#D4AF37',
    textColor: '#F7F2E7',
    accentColor: '#C5A059',
  },
  {
    id: 'tokyo-pastel',
    nameAr: 'طوكيو ساكورا باستيل (Harajuku)',
    bgColor: '#FDF2F5',
    borderColor: '#FBCFE8',
    textColor: '#831843',
    accentColor: '#F43F5E',
  },
  {
    id: 'kinfolk-ivory',
    nameAr: 'كينفولك عاجي نقي (Editorial)',
    bgColor: '#FCFBF9',
    borderColor: '#E7E5E0',
    textColor: '#18181B',
    accentColor: '#A8A29E',
  },
  {
    id: 'analog-35mm',
    nameAr: 'فيلم 35mm كوداك ريترو',
    bgColor: '#1A1715',
    borderColor: '#2E2824',
    textColor: '#FEF08A',
    accentColor: '#F97316',
  },
  {
    id: 'polaroid-cream',
    nameAr: 'بولارويد كريمي دافئ',
    bgColor: '#F7F5EE',
    borderColor: '#E5E0D2',
    textColor: '#292524',
    accentColor: '#D97706',
  },
  {
    id: 'warm-amber',
    nameAr: 'عنبر القهوة الدافئ',
    bgColor: '#FFFBEB',
    borderColor: '#FDE68A',
    textColor: '#78350F',
    accentColor: '#B45309',
  },
  {
    id: 'terracotta-clay',
    nameAr: 'طمي وتيراكوتا',
    bgColor: '#FAF5F0',
    borderColor: '#E2C4B1',
    textColor: '#431407',
    accentColor: '#C2410C',
  },
  {
    id: 'olive-garden',
    nameAr: 'زيتوني هادئ وطبيعي',
    bgColor: '#F4F6F0',
    borderColor: '#D5DDD0',
    textColor: '#1C2818',
    accentColor: '#4D7C0F',
  },
];

export const DEFAULT_PHOTOBOOTH_FRAMES: PhotoboothFrame[] = [
  {
    id: 'snap-express',
    name: 'The Snap Express',
    nameAr: 'تذكرة قطار الذكريات',
    bgColor: '#FAF5EC',
    textColor: '#381016',
    borderColor: '#4A121A',
    accentColor: '#8B2635',
    cornerEmojis: {
      topRight: 'EST',
      bottomLeft: 'EXP',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 3,
    frameShape: 'rounded',
    borderRadius: 22,
    cardMode: 'ticket_express',
    badgeText: 'THE SNAP EXPRESS',
    templateId: 'snap_express_ticket_2x6',
    layoutType: 'strip_3',
    ticketLabel: 'TRAIN TICKET',
    ticketSeat: 'ROW 15 • SEAT A33',
    isCustom: false,
  },
  {
    id: 'spotify-player',
    name: 'Spotify Photostrip',
    nameAr: 'مشغل سبوتيفاي',
    bgColor: '#384C5A',
    textColor: '#FFFFFF',
    borderColor: '#2E2E34',
    accentColor: '#1DB954',
    cornerEmojis: {
      topRight: 'AUDIO',
      bottomLeft: 'SPOT',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 3,
    frameShape: 'rounded',
    borderRadius: 20,
    cardMode: 'spotify_player',
    badgeText: 'SPOTIFY PHOTOSTRIP',
    templateId: 'spotify_photostrip_2x6',
    layoutType: 'strip_3',
    songTitle: 'Nobody Gets Me',
    songArtist: 'SZA • SOS',
    isCustom: false,
  },
  {
    id: 'ios-gallery-bright',
    name: 'iPhone Gallery Bright',
    nameAr: 'ألبوم صور آيفون النهاري',
    bgColor: '#F2F2F7',
    textColor: '#000000',
    borderColor: '#D1D1D6',
    accentColor: '#007AFF',
    cornerEmojis: {
      topRight: 'EST',
      bottomLeft: 'IOS',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 3,
    frameShape: 'rounded',
    borderRadius: 24,
    cardMode: 'ios_gallery_light',
    badgeText: 'IPHONE GALLERY',
    templateId: 'ios_gallery_light_3cut',
    layoutType: 'strip_3',
    isCustom: false,
  },
  {
    id: 'ios-gallery-dark',
    name: 'iPhone Gallery Dark',
    nameAr: 'ألبوم صور آيفون الليلي',
    bgColor: '#000000',
    textColor: '#FFFFFF',
    borderColor: '#1C1C1E',
    accentColor: '#0A84FF',
    cornerEmojis: {
      topRight: 'NIGHT',
      bottomLeft: 'OLED',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 3,
    frameShape: 'rounded',
    borderRadius: 24,
    cardMode: 'ios_gallery_dark',
    badgeText: 'IPHONE GALLERY',
    templateId: 'ios_gallery_dark_3cut',
    layoutType: 'strip_3',
    isCustom: false,
  },
  {
    id: 'ios-camera',
    name: 'iPhone Camera Reticle',
    nameAr: 'كاميرا آيفون',
    bgColor: '#000000',
    textColor: '#FFFFFF',
    borderColor: '#2C2C2E',
    accentColor: '#FFCC00',
    cornerEmojis: {
      topRight: 'FLASH',
      bottomLeft: 'CAM',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 3,
    frameShape: 'rounded',
    borderRadius: 20,
    cardMode: 'ios_camera',
    badgeText: 'IOS CAMERA',
    templateId: 'ios_camera_3cut',
    layoutType: 'strip_3',
    isCustom: false,
  },
  {
    id: 'ios-imessage',
    name: 'iPhone iMessage Chat',
    nameAr: 'محادثة آي مسج',
    bgColor: '#FFFFFF',
    textColor: '#000000',
    borderColor: '#E5E5EA',
    accentColor: '#34C759',
    cornerEmojis: {
      topRight: 'MSG',
      bottomLeft: 'SEND',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 3,
    frameShape: 'rounded',
    borderRadius: 24,
    cardMode: 'ios_imessage',
    badgeText: 'IMESSAGE MMS',
    templateId: 'ios_imessage_3cut',
    layoutType: 'strip_3',
    isCustom: false,
  },
  {
    id: 'noir-korean',
    name: 'Korean Noir',
    nameAr: 'كوريان نوار فخم',
    bgColor: '#121214',
    textColor: '#F4F4F5',
    borderColor: '#27272A',
    accentColor: '#A1A1AA',
    cornerEmojis: {
      topRight: 'FLASH',
      bottomLeft: 'OLED',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 4,
    frameShape: 'rounded',
    borderRadius: 16,
    cardMode: 'korean_noir',
    badgeText: 'SEOUL 4-CUTS',
    templateId: 'korean_noir_2x6',
    layoutType: 'strip_4',
    isCustom: false,
  },
  {
    id: 'arabica-gold',
    name: '% Arabica Luxury Gold',
    nameAr: '% أرابيكا ذهبي فاخر',
    bgColor: '#14110F',
    textColor: '#F7F2E7',
    borderColor: '#D4AF37',
    accentColor: '#C5A059',
    cornerEmojis: {
      topRight: 'ROYAL',
      bottomLeft: 'BREW',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 3,
    frameShape: 'rounded',
    borderRadius: 16,
    cardMode: 'arabica_luxury_gold',
    badgeText: '% ARABICA GOLD',
    templateId: 'arabica_luxury_gold_2x6',
    layoutType: 'arabica_luxury_gold',
    isCustom: false,
  },
  {
    id: 'tokyo-pastel',
    name: 'Tokyo Pastel Pop',
    nameAr: 'طوكيو باستيل بوب',
    bgColor: '#FDF2F5',
    textColor: '#831843',
    borderColor: '#FBCFE8',
    accentColor: '#F43F5E',
    cornerEmojis: {
      topRight: 'TOKYO',
      bottomLeft: 'STAR',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 4,
    frameShape: 'rounded',
    borderRadius: 16,
    cardMode: 'tokyo_pastel',
    badgeText: 'TOKYO EDITION',
    templateId: 'tokyo_pastel_2x6',
    layoutType: 'tokyo_pastel',
    isCustom: false,
  },
  {
    id: 'kinfolk-minimal',
    name: 'Kinfolk Minimal',
    nameAr: 'كينفولك مينيمال تحريري',
    bgColor: '#FCFBF9',
    textColor: '#18181B',
    borderColor: '#E7E5E0',
    accentColor: '#A8A29E',
    cornerEmojis: {
      topRight: 'ARCH',
      bottomLeft: 'BOTANIC',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 3,
    frameShape: 'rounded',
    borderRadius: 14,
    cardMode: 'kinfolk_minimal',
    badgeText: 'KINFOLK EDITION',
    templateId: 'kinfolk_minimal_2x6',
    layoutType: 'kinfolk_minimal',
    isCustom: false,
  },
  {
    id: 'film-35mm',
    name: '35mm Analogue Film',
    nameAr: 'شريط نيجاتيف 35 مم',
    bgColor: '#1A1715',
    textColor: '#FEF08A',
    borderColor: '#2E2824',
    accentColor: '#F97316',
    cornerEmojis: {
      topRight: 'FILM',
      bottomLeft: 'CAM',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 4,
    frameShape: 'sharp',
    borderRadius: 0,
    cardMode: 'film_35mm',
    badgeText: 'KODAK 400TX',
    templateId: 'film_35mm_2x6',
    layoutType: 'film_35mm',
    isCustom: false,
  },
  {
    id: 'polaroid-vintage',
    name: 'Polaroid 600 Vintage',
    nameAr: 'بولارويد كلاسيكي',
    bgColor: '#F7F5EE',
    textColor: '#292524',
    borderColor: '#E5E0D2',
    accentColor: '#D97706',
    cornerEmojis: {
      topRight: 'SNAP',
      bottomLeft: 'BREW',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 1,
    frameShape: 'polaroid',
    borderRadius: 16,
    cardMode: 'polaroid_vintage',
    badgeText: 'POLAROID 600',
    templateId: 'polaroid_vintage',
    layoutType: 'polaroid_vintage',
    isCustom: false,
  },
  {
    id: 'classic-latte',
    name: 'Classic Latte',
    nameAr: 'كافيه لاتيه كلاسيك',
    bgColor: '#F5F0EB',
    textColor: '#2A1810',
    borderColor: '#E6DCCF',
    accentColor: '#C67D34',
    cornerEmojis: {
      topRight: 'ROAST',
      bottomLeft: 'GOLD',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 3,
    frameShape: 'rounded',
    borderRadius: 16,
    badgeText: 'MEMORIES STUDIO',
    isCustom: false,
  },
  {
    id: 'warm-amber',
    name: 'Warm Amber',
    nameAr: 'عنبر القهوة المختصة',
    bgColor: '#FFFBEB',
    textColor: '#78350F',
    borderColor: '#FDE68A',
    accentColor: '#B45309',
    cornerEmojis: {
      topRight: 'ROAST',
      bottomLeft: 'BAKE',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 3,
    frameShape: 'rounded',
    borderRadius: 16,
    badgeText: 'SPECIALTY ROASTERS',
    isCustom: false,
  },
  {
    id: 'terracotta-clay',
    name: 'Terracotta',
    nameAr: 'طمي وتيراكوتا',
    bgColor: '#FAF5F0',
    textColor: '#431407',
    borderColor: '#E2C4B1',
    accentColor: '#C2410C',
    cornerEmojis: {
      topRight: 'CRAFT',
      bottomLeft: 'ORIGIN',
      enabled: true,
    },
    orientation: 'vertical',
    shotCount: 3,
    frameShape: 'rounded',
    badgeText: 'TERRACOTTA WARMTH',
    isCustom: false,
  },
];

export const BUSINESS_INDUSTRY_OPTIONS = [
  {
    id: 'cafe',
    nameAr: 'كافيه ومحمصة مختصة',
    nameEn: 'Cafe & Specialty Roastery',
    icon: 'coffee',
    defaultGiftTitle: 'مشروب سبيشالتي مجاني',
    defaultGiftSubtitle: 'أظهر الكارت للباريستا لاستلام مشروبك المجاني',
    staffLabel: 'الباريستا',
  },
  {
    id: 'restaurant',
    nameAr: 'مطعم ومفهوم طعام',
    nameEn: 'Restaurant & Dining',
    icon: 'dining',
    defaultGiftTitle: 'طبق حلى أو مقبلات مجانية',
    defaultGiftSubtitle: 'أظهر الكارت لموظف الخدمة لاستلام طبقك المجاني',
    staffLabel: 'مقدم الخدمة',
  },
  {
    id: 'retail',
    nameAr: 'متجر ملابس وبوتيك أزياء',
    nameEn: 'Fashion Boutique & Retail',
    icon: 'retail',
    defaultGiftTitle: 'خصم 20% أو قسيمة شراء',
    defaultGiftSubtitle: 'أظهر الكارت للكاشير لتطبيق الخصم فوراً',
    staffLabel: 'الكاشير',
  },
  {
    id: 'salon',
    nameAr: 'صالون تجميل وعناية وسبا',
    nameEn: 'Beauty Salon, Barber & Spa',
    icon: 'salon',
    defaultGiftTitle: 'جلسة عناية أو استشوار مجاني',
    defaultGiftSubtitle: 'أظهر الكارت للاستقبال لتفعيل الجلسة المجانية',
    staffLabel: 'الاستقبال',
  },
  {
    id: 'entertainment',
    nameAr: 'ترفيه، بولينج وملاهي',
    nameEn: 'Entertainment & Gaming',
    icon: 'gaming',
    defaultGiftTitle: 'جولة لعب إضافية مجاناً',
    defaultGiftSubtitle: 'أظهر الكارت لمسؤول الألعاب لبدء جولتك المجانية',
    staffLabel: 'مشرف الألعاب',
  },
  {
    id: 'events',
    nameAr: 'معارض وفعاليات ومؤتمرات',
    nameEn: 'Events & Popups',
    icon: 'events',
    defaultGiftTitle: 'هدية تذكارية خاصة بالفعالية',
    defaultGiftSubtitle: 'أظهر الكارت لمنظمي الفعالية لاستلام هديتك',
    staffLabel: 'منظم الفعالية',
  },
  {
    id: 'general',
    nameAr: 'مساحات وتجارب أخرى',
    nameEn: 'General Business & Spaces',
    icon: 'general',
    defaultGiftTitle: 'هدية أو مكافأة خاصة بالعملاء الأوفياء',
    defaultGiftSubtitle: 'أظهر الكارت لفريق المكان لاستلام مكافأتك',
    staffLabel: 'فريق المكان',
  },
] as const;

export const DEFAULT_BUSINESS_SETTINGS: BusinessSettings = {
  cafeSlug: 'espresso-lab',
  cafeName: 'memories • Café Moments',
  businessType: 'cafe',
  branding: {
    name: 'memories',
    logoUrl: '',
    tagline: 'CAFÉ MOMENTS. LASTING LOYALTY.',
  },
  defaultShotCount: 3,
  defaultOrientation: 'vertical',
  defaultFrameShape: 'rounded',
  defaultBorderRadius: 22,
  defaultDimensionsPreset: 'strip_2x6',
  defaultWidthCm: 5,
  defaultHeightCm: 15.2,
  defaultCardMode: 'ticket_express',
  defaultTemplateId: 'snap_express_ticket_2x6',
  lockFrameForCustomers: true,
  freeGiftOffer: {
    title: 'مشروب مجاني أو هدية فورية',
    subtitle: 'أظهر هذا الشريط لفريق المكان لاستلام هديتك مع الصورة المطبوعة',
    icon: 'reward',
  },
  activeFrameId: 'snap-express',
  activeColorPaletteId: 'ticket-express-cream',
  allowCustomerColorChoice: true,
  allowedColorIds: [
    'ticket-express-cream',
    'spotify-slate-blue',
    'spotify-warm-taupe',
    'spotify-charcoal-oled',
    'spotify-burnt-terracotta',
    'ios-clean-white',
    'ios-oled-black',
    'memories-signature',
    'memories-forest',
    'classic-latte',
    'noir-korean',
    'arabica-gold',
    'tokyo-pastel',
    'kinfolk-ivory',
    'analog-35mm',
    'polaroid-cream',
    'warm-amber',
    'terracotta-clay',
  ],
  allowCustomerStickers: true,
  allowCustomerModeChoice: true,
  allowedModes: [
    'ticket_express',
    'spotify_player',
    'ios_gallery_light',
    'ios_gallery_dark',
    'ios_camera',
    'ios_imessage',
    'korean_noir',
    'tokyo_pastel',
    'kinfolk_minimal',
    'film_35mm',
    'arabica_luxury_gold',
    'polaroid_vintage',
    'cafe_latte',
    'wide_duo_2cut',
    'cinema_horizontal',
  ],
  frames: DEFAULT_PHOTOBOOTH_FRAMES,
};

export const PRESET_EMOJI_PAIRS = [
  { label: 'كلاسيك واستوديو', topRight: 'EST', bottomLeft: 'FILM' },
  { label: 'طوكيو وكارد', topRight: 'TOKYO', bottomLeft: 'LOVE' },
  { label: 'قهوة ومخبوزات', topRight: 'ROAST', bottomLeft: 'BAKE' },
  { label: 'فلاش ونوار', topRight: 'FLASH', bottomLeft: 'OLED' },
  { label: 'كاميرا وتوثيق', topRight: 'SNAP', bottomLeft: 'CAM' },
  { label: 'عصري وناعم', topRight: 'CHIC', bottomLeft: 'MINT' },
  { label: 'عنبر دافئ', topRight: 'HONEY', bottomLeft: 'AMBER' },
  { label: 'ذهبي ملكي', topRight: 'ROYAL', bottomLeft: 'GOLD' },
];

export interface DimensionPreset {
  id: string;
  nameAr: string;
  nameEn: string;
  dimensions: string;
  dimensionsCm: string;
  widthCm: number;
  heightCm: number;
  orientation: StripOrientation;
  aspectRatioLabel: string;
  descriptionAr: string;
}

export const DIMENSION_PRESETS: DimensionPreset[] = [
  {
    id: 'strip_2x6',
    nameAr: 'شريط فوتوبوث كلاسيكي (2×6 بوصة)',
    nameEn: 'Classic Photobooth Strip (2x6 in)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    widthCm: 5,
    heightCm: 15.2,
    orientation: 'vertical',
    aspectRatioLabel: '1:3 (رأسي طولي)',
    descriptionAr: 'الشريط الطولي الأكثر شهرة في استوديوهات كوريا (Seoul 4-Cuts)',
  },
  {
    id: 'grid_4x6',
    nameAr: 'كارت بوستكارد / شبكة (4×6 بوصة)',
    nameEn: 'Postcard / Grid Card (4x6 in)',
    dimensions: '4x6 in',
    dimensionsCm: '10 × 15.2 سم',
    widthCm: 10,
    heightCm: 15.2,
    orientation: 'vertical',
    aspectRatioLabel: '2:3 (بوستكارد قياسي)',
    descriptionAr: 'مقاس الصور القياسي المفضل للطباعة وشبكات 2×2 و2×3 المدمجة',
  },
  {
    id: 'wide_4x3',
    nameAr: 'كارت مكتبي عريض (4×3 بوصة)',
    nameEn: 'Wide Duo Card (4x3 in)',
    dimensions: '4x3 in',
    dimensionsCm: '10 × 7.6 سم',
    widthCm: 10,
    heightCm: 7.6,
    orientation: 'horizontal',
    aspectRatioLabel: '4:3 (أفقي عريض)',
    descriptionAr: 'كارت عريض وقصير مريح للعرض المكتبي ومناسب لصورتين جنباً إلى جنب',
  },
  {
    id: 'polaroid_vintage',
    nameAr: 'بولارويد كلاسيكي (3.5×4.2 بوصة)',
    nameEn: 'Vintage Polaroid (3.5x4.2 in)',
    dimensions: '3.5x4.2 in',
    dimensionsCm: '8.8 × 10.7 سم',
    widthCm: 8.8,
    heightCm: 10.7,
    orientation: 'vertical',
    aspectRatioLabel: '1:1.2 (ذقن عريض)',
    descriptionAr: 'حجم الكاميرات الفورية الأيقوني مع الذقن الأبيض العريض الشهير',
  },
  {
    id: 'cinema_6x2',
    nameAr: 'شريط سينمائي بانورامي (6×2 بوصة)',
    nameEn: 'Cinema Panoramic Strip (6x2 in)',
    dimensions: '6x2 in',
    dimensionsCm: '15.2 × 5 سم',
    widthCm: 15.2,
    heightCm: 5,
    orientation: 'horizontal',
    aspectRatioLabel: '16:9 سينمائي',
    descriptionAr: '3 كادرات سينمائية عريضة بتنسيق لقطات الأفلام والشاشات',
  },
  {
    id: 'custom',
    nameAr: 'أبعاد مخصصة (Custom Dimensions)',
    nameEn: 'Custom Dimensions (cm)',
    dimensions: 'Custom',
    dimensionsCm: 'مخصص',
    widthCm: 7.5,
    heightCm: 12,
    orientation: 'vertical',
    aspectRatioLabel: 'مخصص حسب الرغبة',
    descriptionAr: 'حدد العرض والارتفاع بالسنتيمتر بحرية تامة حسب نوع الطابعة أو الورق',
  },
];

export interface ShotCountOption {
  count: number;
  labelAr: string;
  nameEn: string;
  badge: string;
  descriptionAr: string;
}

export const SHOT_COUNT_OPTIONS: ShotCountOption[] = [
  {
    count: 1,
    labelAr: '1 لقطة واحدة (Grand Solo)',
    nameEn: 'Single Grand Shot',
    badge: '1-CUT',
    descriptionAr: 'صورة واحدة مميزة وبارزة بحجم كامل تبرز تفاصيل اللحظة',
  },
  {
    count: 2,
    labelAr: '2 لقطتان (Double Shot / Duo)',
    nameEn: 'Duo Shots',
    badge: '2-CUTS',
    descriptionAr: 'صورتان متناسقتان جنباً إلى جنب أو رأسياً للكابلز والأصدقاء',
  },
  {
    count: 3,
    labelAr: '3 لقطات (Roastery Trio)',
    nameEn: 'Trio Classic',
    badge: '3-CUTS',
    descriptionAr: 'الشريط الثلاثي الكلاسيكي المريح للعين في كروت ولاء الكافيهات',
  },
  {
    count: 4,
    labelAr: '4 لقطات (Seoul 4-Cuts)',
    nameEn: 'Seoul 4-Cuts',
    badge: '4-CUTS',
    descriptionAr: 'النمط الكوري الشهير عالمياً على بنترست واستوديوهات الصور الفورية',
  },
  {
    count: 6,
    labelAr: '6 لقطات (Story Grid / 6-Pack)',
    nameEn: '6-Cuts Story Grid',
    badge: '6-CUTS',
    descriptionAr: 'شبكة كروت متكاملة 2×3 لتوثيق جميع تفاصيل الزيارة والتجربة',
  },
];

export interface PhotoboothModeInfo {
  id: PhotoboothCardMode;
  nameAr: string;
  nameEn: string;
  icon: string;
  description: string;
  defaultBg: string;
  defaultBorder: string;
  defaultText: string;
  defaultAccent: string;
  filmBadge: string;
  widthCm?: number;
  heightCm?: number;
}

export const PHOTOBOOTH_CARD_MODES: PhotoboothModeInfo[] = [
  {
    id: 'ticket_express',
    nameAr: 'تذكرة قطار الذكريات (The Snap Express)',
    nameEn: 'The Snap Express Vintage Ticket',
    icon: 'ticket',
    description: 'تذكرة قطار وسفر كلاسيكية فاخرة؛ إطار مقوس، لوكوموتيف بخاري، وتذييل تذكرة الراكب والكابينة',
    defaultBg: '#FAF5EC',
    defaultBorder: '#4A121A',
    defaultText: '#381016',
    defaultAccent: '#8B2635',
    filmBadge: 'THE SNAP EXPRESS // TRAIN TICKET',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'spotify_player',
    nameAr: 'مشغل سبوتيفاي (Spotify Photostrip)',
    nameEn: 'Spotify Music Player Photostrip',
    icon: 'music',
    description: 'شريط الأغاني والموسيقى الشهير؛ اسم التراك، فنان اللحظة، شريط التمرير الزمني، وأزرار التحكم',
    defaultBg: '#1E1E22',
    defaultBorder: '#2E2E34',
    defaultText: '#FFFFFF',
    defaultAccent: '#1DB954',
    filmBadge: 'SPOTIFY PHOTOSTRIP #03',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'ios_gallery_light',
    nameAr: 'ألبوم آيفون النهاري (iPhone Photos Light)',
    nameEn: 'iPhone Gallery (Bright Mode)',
    icon: 'phone',
    description: 'واجهة ألبوم صور آبل البيضاء الأصلية؛ شريط حالة iOS، ترويسة Albums، والتاب بار الأزرق',
    defaultBg: '#F2F2F7',
    defaultBorder: '#D1D1D6',
    defaultText: '#000000',
    defaultAccent: '#007AFF',
    filmBadge: 'IPHONE GALLERY // BRIGHT MODE',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'ios_gallery_dark',
    nameAr: 'ألبوم آيفون الليلي (iPhone Photos OLED Dark)',
    nameEn: 'iPhone Gallery (Dark Mode)',
    icon: 'dark',
    description: 'واجهة ألبوم صور آبل بالوضع الليلي شاشات أوليد؛ سواد عميق، نصوص ناصعة، وشريط حالة 9:41',
    defaultBg: '#000000',
    defaultBorder: '#1C1C1E',
    defaultText: '#FFFFFF',
    defaultAccent: '#0A84FF',
    filmBadge: 'IPHONE GALLERY // DARK MODE',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'ios_camera',
    nameAr: 'كاميرا آيفون (iPhone Camera Viewfinder)',
    nameEn: 'iPhone Camera Reticle',
    icon: 'camera',
    description: 'واجهة كاميرا iOS الشهيرة؛ أدوات التصوير العلوية، فوكس أصفر، عجلة PHOTO وزر الشاتر الأبيض',
    defaultBg: '#000000',
    defaultBorder: '#2C2C2E',
    defaultText: '#FFFFFF',
    defaultAccent: '#FFCC00',
    filmBadge: 'IOS CAMERA // PHOTO 4:3',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'ios_imessage',
    nameAr: 'محادثة آيفون (iMessage Chat Strip)',
    nameEn: 'iPhone iMessage Chat Strip',
    icon: 'message',
    description: 'محادثة آي مسج أبل الودية؛ ترويسة جهة الاتصال، فقاعات صور بالقلوب والتفاعلات، وشريط الإرسال',
    defaultBg: '#FFFFFF',
    defaultBorder: '#E5E5EA',
    defaultText: '#000000',
    defaultAccent: '#34C759',
    filmBadge: 'IMESSAGE // NEW MMS',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'korean_noir',
    nameAr: 'نوار كوري فخم (Seoul Vintage 4-Cuts)',
    nameEn: 'Korean Noir (Seoul Studio)',
    icon: 'dark',
    description: 'طابع استوديوهات سول الكورية؛ تباين داكن عالي، تايبوغرافي عصري ناصع البياض، تاريخ نقطي وباركود',
    defaultBg: '#121214',
    defaultBorder: '#27272A',
    defaultText: '#F4F4F5',
    defaultAccent: '#A1A1AA',
    filmBadge: 'SEOUL 4-CUTS // 35MM ISO 400',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'tokyo_pastel',
    nameAr: 'طوكيو باستيل بوب (Harajuku Sakura)',
    nameEn: 'Tokyo Pastel Pop',
    icon: 'sakura',
    description: 'تدرجات ألوان هاراجوكو الباستيلية الراقية، إطارات كيوت ناعمة، وختم التاريخ الرقمي البرتقالي الشهير',
    defaultBg: '#FDF2F5',
    defaultBorder: '#FBCFE8',
    defaultText: '#831843',
    defaultAccent: '#F43F5E',
    filmBadge: 'メモリー・スタジオ // TOKYO PASTEL',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'kinfolk_minimal',
    nameAr: 'كينفولك مينيمال فاخر (Editorial Luxury)',
    nameEn: 'Kinfolk Minimalist Editorial',
    icon: 'kinfolk',
    description: 'أناقة تحريرية للمجلات الفاخرة؛ مساحات تنفس واسعة (Negative Space)، خطوط سيريف رقيقة، وهوامش عاجية نقية',
    defaultBg: '#FCFBF9',
    defaultBorder: '#E7E5E0',
    defaultText: '#18181B',
    defaultAccent: '#A8A29E',
    filmBadge: 'KINFOLK EDITION // VOLUME IV',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'film_35mm',
    nameAr: 'فيلم 35mm تناظري أصلي (Sprocket Holes)',
    nameEn: '35mm Analogue Film Roll',
    icon: 'film',
    description: 'شريط نيجاتيف تناظري كوداك أصلي مع ثقوب التروس الجانبية (Sprockets)، أرقام الكادرات ► 01، وعلامات DX',
    defaultBg: '#1A1715',
    defaultBorder: '#2E2824',
    defaultText: '#FEF08A',
    defaultAccent: '#F97316',
    filmBadge: 'KODAK 400TX // 35MM SAFETY FILM',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'arabica_luxury_gold',
    nameAr: '% أرابيكا ذهبي فاخر (Espresso & Gold Foil)',
    nameEn: '% Arabica Luxury Gold',
    icon: 'gold',
    description: 'إسبريسو داكن غير لامع مع إطار ذهبي ميتاليك براق ولمسات فخامة كافيهات القهوة المختصة الفاخرة',
    defaultBg: '#14110F',
    defaultBorder: '#D4AF37',
    defaultText: '#F7F2E7',
    defaultAccent: '#C5A059',
    filmBadge: '% ARABICA // LUXURY GOLD EDITION',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'polaroid_vintage',
    nameAr: 'بولارويد كلاسيكي أصلي (Wide Chin)',
    nameEn: 'Classic Vintage Polaroid',
    icon: 'polaroid',
    description: 'إطار الكاميرا الفورية العريض مع الذقن السفلي الشهير لكتابة التوقيع بالخط اليدوي وملمس الورق الدافئ',
    defaultBg: '#F7F5EE',
    defaultBorder: '#E5E0D2',
    defaultText: '#292524',
    defaultAccent: '#D97706',
    filmBadge: 'POLAROID 600 // INSTANT PRINT',
    widthCm: 8.8,
    heightCm: 10.7,
  },
  {
    id: 'cafe_latte',
    nameAr: 'كافيه روستري بورسلين (Specialty Roastery)',
    nameEn: 'Cafe Specialty Roastery',
    icon: 'coffee',
    description: 'ورق بورسلين كريمي دافئ ملمسي، ترويسة روستري الحرفية، ونصوص بلون الإسبريسو',
    defaultBg: '#FAF6F0',
    defaultBorder: '#EADFD3',
    defaultText: '#2B1810',
    defaultAccent: '#B46B34',
    filmBadge: 'SPECIALTY ROASTERS // SINGLE ORIGIN',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'wide_duo_2cut',
    nameAr: 'الكارت العريض القصير (صورتين جنب بعض)',
    nameEn: 'Wide Duo Postcard',
    icon: 'frame',
    description: 'كارت عريض وقصير متوازن ومريح؛ صورتان أفقيتان جنباً إلى جنب بهوامش استوديو ناعمة',
    defaultBg: '#FBF9F5',
    defaultBorder: '#E8E2D8',
    defaultText: '#1A1A1A',
    defaultAccent: '#C2410C',
    filmBadge: 'MEMORIES POSTCARD // EDITION 02',
    widthCm: 10,
    heightCm: 7.6,
  },
  {
    id: 'cinema_horizontal',
    nameAr: 'شريط سينمائي 16:9 بانورامي',
    nameEn: 'Cinema Widescreen',
    icon: 'cinema',
    description: '3 كادرات عريضة بنسبة 16:9 بأسلوب لقطات الأفلام السينمائية مع ترويسة رقم المشهد',
    defaultBg: '#09090B',
    defaultBorder: '#18181B',
    defaultText: '#E4E4E7',
    defaultAccent: '#EAB308',
    filmBadge: 'CINEMA SCOPE 2.39:1 // SCENE 01',
    widthCm: 15.2,
    heightCm: 5,
  },
  {
    id: 'retro_film',
    nameAr: 'فيلم 35mm ريترو سينمائي (Sprocket Holes)',
    nameEn: 'Retro 35mm Analog Film',
    icon: 'film',
    description: 'طابع شرائط الأفلام التناظرية مع ثقوب التروس الجانبية وعلامات الكوداك والـ 35 مم',
    defaultBg: '#1A1715',
    defaultBorder: '#2E2824',
    defaultText: '#FEF08A',
    defaultAccent: '#F97316',
    filmBadge: 'KODAK SAFETY FILM 400 // DX CODE',
    widthCm: 5,
    heightCm: 15.2,
  },
  {
    id: 'polaroid_classic',
    nameAr: 'بولارويد كلاسيكي أصلي (Wide Chin)',
    nameEn: 'Classic Polaroid',
    icon: 'polaroid',
    description: 'إطار الكاميرا الفورية المربع مع الحافة السفلية العريضة الشهيرة لكتابة التاريخ أو التوقيع',
    defaultBg: '#F7F5EE',
    defaultBorder: '#E5E0D2',
    defaultText: '#292524',
    defaultAccent: '#D97706',
    filmBadge: 'ORIGINAL INSTANT PRINT // 600 FILM',
    widthCm: 8.8,
    heightCm: 10.7,
  },
  {
    id: 'arabica_monochrome',
    nameAr: '% أرابيكا مونوكروم استوديو',
    nameEn: '% Arabica Monochrome',
    icon: 'star',
    description: 'تصميم هندسي فائق النقاء بالأبيض والأسود مع تايبوغرافي قوي مستوحى من المقاهي اليابانية',
    defaultBg: '#FFFFFF',
    defaultBorder: '#000000',
    defaultText: '#000000',
    defaultAccent: '#737373',
    filmBadge: '% MEMORIES // KYOTO DESIGN',
    widthCm: 5,
    heightCm: 15.2,
  },
];

export const CURATED_STICKER_SET = [
  'MEMORIES', 'COFFEE', 'SPECIALTY', 'ARTISAN', 'STUDIO', 'EST.2026', 'MOMENT', 'ORIGIN',
  'BOTANIC', 'PARIS', 'MILAN', 'SEOUL', 'TOKYO', 'LONDON', 'KYOTO', 'VIBE',
];

export const PHOTOBOOTH_FRAME_TEMPLATES: PhotoboothFrameTemplate[] = [
  {
    id: 'snap_express_ticket_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: 'The Snap Express (3 Cuts Ticket)',
    nameAr: 'تذكرة قطار الذكريات (The Snap Express - 3 لقطات)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 3,
    layoutType: 'strip_3',
    cardMode: 'ticket_express',
    description: 'تذكرة قطار بخاري وسفر كلاسيكية مع إطار مقوس مزدوج وتذييل الراكب والمقعد',
    badge: 'VINTAGE TICKET',
    icon: 'ticket',
    defaultBg: '#FAF5EC',
    defaultBorder: '#4A121A',
    defaultText: '#381016',
    defaultAccent: '#8B2635',
  },
  {
    id: 'spotify_photostrip_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: 'Spotify Music Photostrip (3 Cuts)',
    nameAr: 'مشغل سبوتيفاي الموسيقي (3 لقطات)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 3,
    layoutType: 'strip_3',
    cardMode: 'spotify_player',
    description: 'شريط مشغل الأغاني الأيقوني مع تراك اللحظة، شريط الوقت، وأزرار التحكم بالصوت والتشغيل',
    badge: 'SPOTIFY #03',
    icon: 'music',
    defaultBg: '#1E1E22',
    defaultBorder: '#2E2E34',
    defaultText: '#FFFFFF',
    defaultAccent: '#1DB954',
  },
  {
    id: 'iphone_gallery_light_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: 'iPhone Photos Light (3 Cuts)',
    nameAr: 'ألبوم آيفون النهاري (3 لقطات - Bright Mode)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 3,
    layoutType: 'strip_3',
    cardMode: 'ios_gallery_light',
    description: 'واجهة تطبيق صور آبل الأصلية بالوضع النهاري مع شريط الساعة والتاب بار السفلي',
    badge: 'IOS BRIGHT',
    icon: 'phone',
    defaultBg: '#F2F2F7',
    defaultBorder: '#D1D1D6',
    defaultText: '#000000',
    defaultAccent: '#007AFF',
  },
  {
    id: 'iphone_gallery_dark_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: 'iPhone Photos OLED Dark (3 Cuts)',
    nameAr: 'ألبوم آيفون الليلي (3 لقطات - Dark Mode)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 3,
    layoutType: 'strip_3',
    cardMode: 'ios_gallery_dark',
    description: 'واجهة تطبيق صور آبل بالوضع الليلي شاشات OLED الداكنة مع نصوص واضحة وعصرية',
    badge: 'IOS DARK',
    icon: 'dark',
    defaultBg: '#000000',
    defaultBorder: '#1C1C1E',
    defaultText: '#FFFFFF',
    defaultAccent: '#0A84FF',
  },
  {
    id: 'iphone_camera_strip_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: 'iPhone Camera Viewfinder (3 Cuts)',
    nameAr: 'كاميرا آيفون فيوفايندر (3 لقطات)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 3,
    layoutType: 'strip_3',
    cardMode: 'ios_camera',
    description: 'واجهة تصوير كاميرا آبل؛ شريط الأدوات العلوي، فوكس أصفر، عجلة الأوضاع وزر الشاتر الأبيض',
    badge: 'IOS CAMERA',
    icon: 'camera',
    defaultBg: '#000000',
    defaultBorder: '#2C2C2E',
    defaultText: '#FFFFFF',
    defaultAccent: '#FFCC00',
  },
  {
    id: 'iphone_imessage_strip_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: 'iPhone iMessage Chat (3 Cuts)',
    nameAr: 'محادثة آي مسج (3 لقطات)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 3,
    layoutType: 'strip_3',
    cardMode: 'ios_imessage',
    description: 'شريط محادثة آبل الودية مع فقاعات الصور وتفاعلات القلوب والملصقات وشريط الرسائل',
    badge: 'IMESSAGE',
    icon: 'message',
    defaultBg: '#FFFFFF',
    defaultBorder: '#E5E5EA',
    defaultText: '#000000',
    defaultAccent: '#34C759',
  },
  {
    id: 'korean_noir_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: 'Korean Noir Strip (4 Cuts)',
    nameAr: 'الشريط الكوري الأسود (4 لقطات - Seoul Studio)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 4,
    layoutType: 'strip_4',
    cardMode: 'korean_noir',
    description: 'الأكثر شهرة على بنترست وفي استوديوهات سول؛ 4 صور رأسية أنيقة بحدود بيضاء رقيقة وتاريخ نقطي وباركود',
    badge: 'SEOUL 4-CUTS',
    icon: 'dark',
    defaultBg: '#121214',
    defaultBorder: '#27272A',
    defaultText: '#F4F4F5',
    defaultAccent: '#A1A1AA',
  },
  {
    id: 'tokyo_pastel_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: 'Tokyo Pastel Pop (4 Cuts)',
    nameAr: 'طوكيو باستيل بوب (4 لقطات - Harajuku Sakura)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 4,
    layoutType: 'tokyo_pastel',
    cardMode: 'tokyo_pastel',
    description: 'درجات الوردي الباستيل الهادئ مع كتابة يابانية أنيقة وختم تاريخ رقمي برتقالي بأسلوب طوكيو',
    badge: 'TOKYO EDITION',
    icon: 'sakura',
    defaultBg: '#FDF2F5',
    defaultBorder: '#FBCFE8',
    defaultText: '#831843',
    defaultAccent: '#F43F5E',
  },
  {
    id: 'kinfolk_minimal_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: 'Kinfolk Minimalist (3 Cuts)',
    nameAr: 'كينفولك مينيمال تحريري (3 لقطات - Editorial Luxury)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 3,
    layoutType: 'kinfolk_minimal',
    cardMode: 'kinfolk_minimal',
    description: '3 لقطات بهوامش ومساحات تنفس واسعة وتصميم نقي باللون العاجي مع خطوط سيريف دقيقة جداً',
    badge: 'KINFOLK EDITION',
    icon: 'kinfolk',
    defaultBg: '#FCFBF9',
    defaultBorder: '#E7E5E0',
    defaultText: '#18181B',
    defaultAccent: '#A8A29E',
  },
  {
    id: 'film_35mm_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: 'Analog 35mm Film (4 Cuts)',
    nameAr: 'شريط نيجاتيف 35 مم ريترو (4 لقطات - Sprockets)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 4,
    layoutType: 'film_35mm',
    cardMode: 'film_35mm',
    description: 'شريط فيلم كوداك حقيقي مع ثقوب التروس الجانبية وأرقام الكادرات الفيلمية والباركود التناظري',
    badge: 'KODAK 400TX',
    icon: 'film',
    defaultBg: '#1A1715',
    defaultBorder: '#2E2824',
    defaultText: '#FEF08A',
    defaultAccent: '#F97316',
  },
  {
    id: 'arabica_luxury_gold_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: '% Arabica Luxury Gold (3 Cuts)',
    nameAr: '% أرابيكا ذهبي فاخر (3 لقطات - Dark Espresso & Gold)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 3,
    layoutType: 'arabica_luxury_gold',
    cardMode: 'arabica_luxury_gold',
    description: 'خلفية إسبريسو داكنة غير لامعة مع إطار ذهبي ميتاليك براق وخطوط فاخرة مستوحاة من محامص النخبة',
    badge: '% ARABICA GOLD',
    icon: 'gold',
    defaultBg: '#14110F',
    defaultBorder: '#D4AF37',
    defaultText: '#F7F2E7',
    defaultAccent: '#C5A059',
  },
  {
    id: 'polaroid_vintage',
    widthCm: 8.8,
    heightCm: 10.7,
    nameEn: 'Polaroid 600 Vintage (1 Cut)',
    nameAr: 'بولارويد كلاسيكي مربع (لقطة واحدة - Wide Chin)',
    dimensions: '3.5x4.2 in',
    dimensionsCm: '8.8 × 10.7 سم',
    orientation: 'vertical',
    shotCount: 1,
    layoutType: 'polaroid_vintage',
    cardMode: 'polaroid_vintage',
    description: 'الإطار الأيقوني لكاميرات البولارويد؛ صورة مربعة 1:1 مع ذقن أبيض عريض لكتابة التوقيع أو التاريخ باليد',
    badge: 'POLAROID 600',
    icon: 'polaroid',
    defaultBg: '#F7F5EE',
    defaultBorder: '#E5E0D2',
    defaultText: '#292524',
    defaultAccent: '#D97706',
  },
  {
    id: 'grid_4x6_4cut',
    widthCm: 10,
    heightCm: 15.2,
    nameEn: 'Postcard 4x6 Grid (4 Cuts)',
    nameAr: 'شبكة بوستكارد 4×6 (4 لقطات - Grid 2x2)',
    dimensions: '4x6 in',
    dimensionsCm: '10 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 4,
    layoutType: 'grid_2x2',
    cardMode: 'korean_noir',
    description: 'كارت قياسي 4×6 بوصة بتوزيع شبكي متناسق 2×2 مثالي للمجموعات واللقطات الرباعية',
    badge: 'POSTCARD 2x2',
    icon: 'studio',
    defaultBg: '#121214',
    defaultBorder: '#27272A',
    defaultText: '#F4F4F5',
    defaultAccent: '#A1A1AA',
  },
  {
    id: 'grid_4x6_6cut',
    widthCm: 10,
    heightCm: 15.2,
    nameEn: 'Postcard 4x6 Story Grid (6 Cuts)',
    nameAr: 'شبكة ذكريات 4×6 (6 لقطات - Grid 2x3)',
    dimensions: '4x6 in',
    dimensionsCm: '10 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 6,
    layoutType: 'grid_2x3',
    cardMode: 'kinfolk_minimal',
    description: 'كارت 6 لقطات مصفوفة في شبكة 2×3 متكاملة لتوثيق تفاصيل اليوم والمكان بالكامل',
    badge: 'STORY GRID 6',
    icon: '▦',
    defaultBg: '#FCFBF9',
    defaultBorder: '#E7E5E0',
    defaultText: '#18181B',
    defaultAccent: '#A8A29E',
  },
  {
    id: 'wide_duo_2cut',
    widthCm: 10,
    heightCm: 7.6,
    nameEn: 'Wide Duo (2 Side-by-Side)',
    nameAr: 'الكارت العريض القصير (صورتين جنب بعض - 10×7.6 سم)',
    dimensions: '4x3 in',
    dimensionsCm: '10 × 7.6 سم',
    orientation: 'horizontal',
    shotCount: 2,
    layoutType: 'wide_duo_2cut',
    cardMode: 'wide_duo_2cut',
    description: 'كارت عريض وقصير مريح جداً؛ صورتان أفقيتان جنباً إلى جنب بهوامش استوديو ناعمة ومظهر أنيق ومتوازن',
    badge: 'WIDE DUO 2',
    icon: 'frame',
    defaultBg: '#FBF9F5',
    defaultBorder: '#E8E2D8',
    defaultText: '#1A1A1A',
    defaultAccent: '#C2410C',
  },
  {
    id: 'cinema_strip_6x2',
    widthCm: 15.2,
    heightCm: 5,
    nameEn: 'Cinema Trio 16:9 (3 Cuts)',
    nameAr: 'الشريط السينمائي البانورامي (3 لقطات - 16:9)',
    dimensions: '6x2 in',
    dimensionsCm: '15.2 × 5 سم',
    orientation: 'horizontal',
    shotCount: 3,
    layoutType: 'cinema_horizontal',
    cardMode: 'cinema_horizontal',
    description: '3 كادرات سينمائية عريضة 16:9 جنباً إلى جنب مع أشرطة لقطات الأفلام وشريط ترجمة وهمي',
    badge: 'CINEMA SCOPE',
    icon: 'cinema',
    defaultBg: '#09090B',
    defaultBorder: '#18181B',
    defaultText: '#E4E4E7',
    defaultAccent: '#EAB308',
  },
  // Aliases for backwards compatibility with existing saved settings:
  {
    id: 'retro_film_35mm',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: 'Analog 35mm Film (4 Cuts)',
    nameAr: 'شريط نيجاتيف 35 مم ريترو (4 لقطات - Sprockets)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 4,
    layoutType: 'film_35mm',
    cardMode: 'film_35mm',
    description: 'شريط فيلم كوداك حقيقي مع ثقوب التروس الجانبية وأرقام الكادرات الفيلمية والباركود التناظري',
    badge: 'KODAK 400TX',
    icon: 'film',
    defaultBg: '#1A1715',
    defaultBorder: '#2E2824',
    defaultText: '#FEF08A',
    defaultAccent: '#F97316',
  },
  {
    id: 'polaroid_classic',
    widthCm: 8.8,
    heightCm: 10.7,
    nameEn: 'Polaroid 600 Square (1 Cut)',
    nameAr: 'بولارويد كلاسيكي مربع (لقطة واحدة - Wide Chin)',
    dimensions: '3.5x4.2 in',
    dimensionsCm: '8.8 × 10.7 سم',
    orientation: 'vertical',
    shotCount: 1,
    layoutType: 'polaroid_vintage',
    cardMode: 'polaroid_vintage',
    description: 'الإطار الأيقوني لكاميرات البولارويد؛ صورة مربعة 1:1 مع ذقن أبيض عريض لكتابة التوقيع أو التاريخ',
    badge: 'POLAROID 600',
    icon: 'polaroid',
    defaultBg: '#F7F5EE',
    defaultBorder: '#E5E0D2',
    defaultText: '#292524',
    defaultAccent: '#D97706',
  },
  {
    id: 'classic_latte_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: 'Café Specialty Roastery (3 Cuts)',
    nameAr: 'كافيه سبيشالتي روستري (3 لقطات - بورسلين دافئ)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 3,
    layoutType: 'strip_3',
    cardMode: 'cafe_latte',
    description: '3 صور عريضة مريحة للعين بلون ورق البورسلين الدافئ وخط أنيق باسم الروستري ونجمة ذهبية',
    badge: 'SPECIALTY ROASTERS',
    icon: 'coffee',
    defaultBg: '#FAF6F0',
    defaultBorder: '#EADFD3',
    defaultText: '#2B1810',
    defaultAccent: '#B46B34',
  },
  {
    id: 'arabica_monochrome_2x6',
    widthCm: 5,
    heightCm: 15.2,
    nameEn: '% Arabica Monochrome (3 Cuts)',
    nameAr: '% أرابيكا مونوكروم (3 لقطات - كيوتو ديزاين)',
    dimensions: '2x6 in',
    dimensionsCm: '5 × 15.2 سم',
    orientation: 'vertical',
    shotCount: 3,
    layoutType: 'arabica_monochrome',
    cardMode: 'arabica_monochrome',
    description: 'تصميم هندسي فائق النقاء بالأبيض والأسود مع تايبوغرافي قوي مستوحى من أرابيكا كيوتو',
    badge: '% ARABICA KYOTO',
    icon: 'star',
    defaultBg: '#FFFFFF',
    defaultBorder: '#000000',
    defaultText: '#000000',
    defaultAccent: '#737373',
  },
];
